// Docker-gated end-to-end test of diagram import (BI-4C17BF51, AC-ODC-010 import
// half): a Visio file and a DPF-exported .odg go through the real dpf-doctools
// engine and come out as candidate elements and relationships.
//
// Runs only when DPF_DOCTOOLS_TEST_IMAGE names a pinned dpf-doctools image
// (`name@sha256:…`, or the local image id `sha256:…` of a fresh
// `docker build -f Dockerfile.doctools`) AND docker answers. Otherwise every
// case is reported SKIPPED, never passed. The Visio fixture is generated by the
// image's own python3 from tools/doctools/fixtures/sample-vsdx.py.

import { spawnSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it, vi } from "vitest";
import { isPinnedImageReference } from "@/lib/documents/conversion/command";
import { convertDocument, createConversionLimiter } from "@/lib/documents/conversion/convert";
import { renderDocument, type RenderDocumentRequest } from "@/lib/documents/generation/render";
import { DEFAULT_DRAWING_TOKENS, exportEaViewDrawingFile } from "../view-drawing-export";
import type { EaViewForDrawing } from "../view-drawing";
import { importDiagramFile, type StagedDiagramImport } from "./import-diagram";

vi.mock("@dpf/db", () => ({ prisma: {} }));

const IMAGE = process.env.DPF_DOCTOOLS_TEST_IMAGE?.trim() ?? "";
const GENERATOR = resolve(__dirname, "../../../../../tools/doctools/fixtures/sample-vsdx.py");

function dockerHasImage(image: string): boolean {
  if (!isPinnedImageReference(image)) return false;
  try {
    // ambient-host-guard: allow the docker gate itself; a host without the image reports this suite SKIPPED
    return spawnSync("docker", ["image", "inspect", image], { stdio: "ignore", timeout: 15_000 }).status === 0;
  } catch {
    return false;
  }
}

function visioFixture(): Buffer {
  // ambient-host-guard: allow the docker gate itself; runs only when the image is present
  const run = spawnSync("docker", ["run", "--rm", "-i", "--network", "none", "--entrypoint", "python3", IMAGE, "-"], {
    input: readFileSync(GENERATOR),
    timeout: 60_000,
    maxBuffer: 10 * 1024 * 1024,
  });
  if (run.status !== 0) throw new Error(`fixture generator failed: ${run.stderr.toString()}`);
  return run.stdout;
}

const ready = dockerHasImage(IMAGE);
const limiter = createConversionLimiter(2);
const engine = { resolveImage: async () => ({ status: "pinned" as const, image: IMAGE }), limiter };

async function importFile(fileName: string, bytes: Buffer): Promise<{ staged: StagedDiagramImport; summary: unknown }> {
  let staged: StagedDiagramImport | null = null;
  const summary = await importDiagramFile(
    { fileName, bytes, userId: "user-1" },
    {
      convert: (request) => convertDocument(request, engine),
      findExisting: async () => null,
      stage: async (input) => {
        staged = input;
        return "imp-1";
      },
    },
  );
  if (!staged) throw new Error(`nothing was staged: ${JSON.stringify(summary)}`);
  return { staged, summary };
}

describe.skipIf(!ready)("diagram import against the real dpf-doctools image", () => {
  it("turns a Visio diagram's shapes and connectors into candidate elements and relationships", async () => {
    const { staged, summary } = await importFile("Order platform.vsdx", visioFixture());
    expect(summary).toMatchObject({ ok: true, data: { elementCount: 4, relationshipCount: 3, unattachedConnectors: 0, previewAvailable: true } });
    const [page] = staged.drawing.pages;
    const label = new Map(page!.elements.map((element) => [element.key, element.label]));
    expect([...label.values()].sort()).toEqual(["Customer Portal", "DPFSENTINELDRAW Billing", "Order Service", "Orders Database"]);
    const pairs = page!.relationships.map((relationship) => [
      [label.get(relationship.fromKey), label.get(relationship.toKey)].sort().join(" <-> "),
      relationship.label,
    ]);
    expect(pairs.sort()).toEqual([
      ["Customer Portal <-> Order Service", "calls"],
      ["DPFSENTINELDRAW Billing <-> Orders Database", null],
      ["Order Service <-> Orders Database", "reads"],
    ]);
    expect(staged.svg?.toString("utf8")).toContain("<svg");
  }, 240_000);

  it("reads back a DPF-exported .odg: every element, every relationship, and its layer", async () => {
    const elements = Array.from({ length: 21 }, (_, index) => ({
      viewElementId: `ve-${index}`,
      parentViewElementId: null,
      orderIndex: null,
      rendererHint: null,
      mode: "new" as const,
      proposedProperties: null,
      elementType: index % 2
        ? { slug: "application_component", name: "Application Component", neoLabel: "ArchiMate__ApplicationComponent" }
        : { slug: "business_process", name: "Business Process", neoLabel: "ArchiMate__BusinessProcess" },
      element: { name: `Element ${index}` },
    }));
    const view: EaViewForDrawing = {
      name: "Round trip",
      elements,
      edges: elements.slice(1).map((element, index) => ({
        id: `r${index}`,
        fromViewElementId: elements[index]!.viewElementId,
        toViewElementId: element.viewElementId,
        relationshipType: { slug: "serves", name: "serves" },
      })),
      canvasState: null,
    };
    const exported = await exportEaViewDrawingFile(
      { viewId: "v", format: "odg" },
      {
        loadView: async () => view,
        loadTokens: async () => DEFAULT_DRAWING_TOKENS,
        render: (request: RenderDocumentRequest) => renderDocument(request, engine),
      },
    );
    if (!exported.ok) throw new Error(exported.error);
    const { staged } = await importFile("Round trip.odg", exported.data.bytes);
    const [page] = staged.drawing.pages;
    expect(page!.elements.map((element) => element.label)).toEqual(elements.map((element) => element.element.name));
    expect(page!.elements.map((element) => element.suggestedLayer)).toEqual(elements.map((_, index) => (index % 2 ? "application" : "business")));
    expect(page!.relationships).toHaveLength(20);
    expect(page!.relationships.every((relationship) => relationship.label === "serves")).toBe(true);
  }, 480_000);
});
