// BI-545943EE: the inline operating contract is generated from the pages that
// state it, never hand-written, and never emitted partially.
import assert from "node:assert/strict";
import { mkdirSync, mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { test } from "node:test";
import { fileURLToPath } from "node:url";

import {
  AGENTS_ANCHOR,
  GENERATED_MODULE_PATH,
  PRINCIPLE_SOURCES,
  buildOperatingContractLines,
  renderGeneratedModule,
} from "./generate-operating-contract.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "..", "..", "..");

function makeRepo({ omit = null, emptyDirection = null, agentsBullet = true } = {}) {
  const root = mkdtempSync(join(tmpdir(), "dpf-operating-contract-"));
  for (const rel of PRINCIPLE_SOURCES) {
    if (rel === omit) continue;
    mkdirSync(dirname(join(root, rel)), { recursive: true });
    const direction = rel === emptyDirection ? "" : `Direction of ${rel}.`;
    writeFileSync(
      join(root, rel),
      `---\ntitle: T\nprincipleDirection: ${direction}\n---\n\n# Body\n`,
      "utf8",
    );
  }
  const agents = agentsBullet
    ? `# Rules\n\n- ${AGENTS_ANCHOR} \`wiki_query\` for lookup.\n- **Other.** text\n`
    : "# Rules\n\n- **Other.** text\n";
  writeFileSync(join(root, "AGENTS.md"), agents, "utf8");
  return root;
}

test("the committed generated module equals a fresh generation", () => {
  const committed = readFileSync(join(repoRoot, GENERATED_MODULE_PATH), "utf8");
  assert.equal(committed, renderGeneratedModule(buildOperatingContractLines(repoRoot)));
});

test("the contract carries the three principle directions and the AGENTS.md doctrine-store rule", () => {
  const lines = buildOperatingContractLines(makeRepo());
  assert.equal(
    lines[0],
    "Operating contract (inline because DPF cannot prove its skills are loaded):",
  );
  assert.equal(
    lines[1],
    "- principles/decisions-belong-to-their-scope: Direction of docs/founder-kernel/wiki/principles/decisions-belong-to-their-scope.md.",
  );
  assert.match(lines[2], /^- principles\/escalation-is-a-gate-not-a-trust-tier: Direction of /);
  assert.match(lines[3], /^- principles\/consult-scopes-before-asking: Direction of /);
  assert.equal(
    lines[4],
    "- AGENTS.md §11: Kernel principles (Surface C) are the durable doctrine store. `wiki_query` for lookup.",
  );
  assert.equal(lines[5], "Before inferring doctrine from source, read the page: wiki_query <slug>.");
  assert.equal(lines.length, 6);
});

test("a frontmatter slug overrides the path-derived slug", () => {
  const root = makeRepo();
  const rel = PRINCIPLE_SOURCES[0];
  writeFileSync(
    join(root, rel),
    "---\nslug: custom/slug\nprincipleDirection: \"Quoted direction.\"\n---\n",
    "utf8",
  );
  assert.equal(buildOperatingContractLines(root)[1], "- custom/slug: Quoted direction.");
});

test("a missing principle page fails loudly", () => {
  assert.throws(
    () => buildOperatingContractLines(makeRepo({ omit: PRINCIPLE_SOURCES[1] })),
    /escalation-is-a-gate-not-a-trust-tier/,
  );
});

test("an empty principleDirection fails loudly", () => {
  assert.throws(
    () => buildOperatingContractLines(makeRepo({ emptyDirection: PRINCIPLE_SOURCES[2] })),
    /principleDirection/,
  );
});

test("a missing AGENTS.md doctrine-store bullet fails loudly", () => {
  assert.throws(
    () => buildOperatingContractLines(makeRepo({ agentsBullet: false })),
    /AGENTS\.md/,
  );
});

test("the generated module is marked generated and exports frozen lines", () => {
  const text = renderGeneratedModule(["a", "b"]);
  assert.match(text, /GENERATED by packages\/dpf-skill-pack\/scripts\/generate-operating-contract\.mjs/);
  assert.match(text, /do not edit/i);
  assert.match(text, /export const OPERATING_CONTRACT_LINES = Object\.freeze\(/);
});
