import type { BusinessCapabilityPerspective, BusinessCapabilitySeedDefinition } from "./business-capability-perspectives";

type CategoryCapabilityLane = {
  key: string;
  name: string;
  description: string;
  it4itValueStreams: string[];
};

type CategoryCapabilityTemplate = {
  perspectiveId: string;
  label: string;
  source: string;
  rootKey: string;
  rootName: string;
  rootDescription: string;
  rootSortOrder: number;
  rootValueStreams: string[];
  lanes: CategoryCapabilityLane[];
};

const BEAUTY_PERSONAL_CARE: BusinessCapabilityPerspective = {
  perspectiveId: "beauty-personal-care",
  label: "Beauty And Personal Care",
  source: "DPF beauty/personal-care overlay informed by appointment checkout, service menu, practitioner assignment, retail/POS payments, CRM/marketing automation, and local-presence operating patterns",
  capabilities: [
    l1(
      "beauty-service-operations",
      "Beauty And Personal Care Operations",
      100,
      "Operate appointment-led personal services across service menus, practitioners, client preferences, checkout, retail products, and local demand channels.",
      ["consume", "operate"],
    ),
    l2(
      "beauty-service-menu-packages",
      "beauty-service-operations",
      "Service Menu Packages And Pricing",
      10,
      "Define services, treatments, add-ons, packages, memberships, prices, durations, booking rules, and product/service bundles.",
      ["explore", "consume"],
    ),
    l2(
      "beauty-booking-practitioner-calendar",
      "beauty-service-operations",
      "Booking Practitioner Calendar",
      20,
      "Coordinate appointment slots, practitioner or stylist assignment, customer-choice booking, buffers, reminders, and schedule exceptions.",
      ["consume", "operate"],
    ),
    l2(
      "beauty-client-preferences-intake",
      "beauty-service-operations",
      "Client Preferences And Intake",
      30,
      "Maintain client records, preferences, sensitivities, consent notes, style or treatment history, and CRM/customer profile anchors.",
      ["consume", "operate"],
    ),
    l2(
      "beauty-checkout-retail-payments",
      "beauty-service-operations",
      "Checkout Retail And Payments",
      40,
      "Handle appointment checkout, deposits, tips, packages, product retail sales, refunds, and Stripe/Square-like POS or payment reconciliation posture.",
      ["consume", "operate", "integrate"],
    ),
    l2(
      "beauty-supplies-tools-stock",
      "beauty-service-operations",
      "Supplies Tools Stock And Procurement",
      50,
      "Track professional products, consumables, tools, equipment, retail stock, restock thresholds, suppliers, and purchasing needs.",
      ["operate"],
    ),
    l2(
      "beauty-local-marketing-reviews",
      "beauty-service-operations",
      "Local Marketing Reviews And Referrals",
      60,
      "Manage Google Business Profile/local presence, social proof, reviews, referrals, email campaigns, promotions, and HubSpot/Mailchimp-style growth anchors.",
      ["explore"],
    ),
  ],
};

const TRADES_MAINTENANCE: BusinessCapabilityPerspective = {
  perspectiveId: "trades-maintenance",
  label: "Trades And Maintenance",
  source: "DPF trades/maintenance overlay informed by field-service dispatch, work-order lifecycle, customer ETA communications, truck stock, subcontractor/safety, and trades finance operating patterns",
  capabilities: [
    l1(
      "trades-field-service-operations",
      "Trades And Maintenance Operations",
      100,
      "Operate field-service work across inquiry intake, dispatch, technician readiness, work orders, customer updates, vehicle stock, subcontractors, and contract billing.",
      ["consume", "operate"],
    ),
    l2(
      "trades-job-intake-triage",
      "trades-field-service-operations",
      "Job Intake And Triage",
      10,
      "Capture job descriptions, urgency, property type, photos, notes, quote requests, emergency call-outs, and customer contact preferences.",
      ["consume"],
    ),
    l2(
      "trades-dispatch-technician-readiness",
      "trades-field-service-operations",
      "Dispatch And Technician Readiness",
      20,
      "Assign technicians or crews, schedule visits, check skills, tools, and parts readiness, and keep dispatcher queues current.",
      ["operate"],
    ),
    l2(
      "trades-work-order-lifecycle",
      "trades-field-service-operations",
      "Work Order Lifecycle",
      30,
      "Track planned maintenance, reactive repair, inspections, site notes, completion evidence, follow-up tasks, and status handoffs.",
      ["operate"],
    ),
    l2(
      "trades-customer-updates-eta",
      "trades-field-service-operations",
      "Customer Updates ETA And Exceptions",
      40,
      "Send appointment confirmations, on-my-way ETA updates, running-late notices, access instructions, and completion follow-ups across communication channels.",
      ["integrate", "operate"],
    ),
    l2(
      "trades-truck-stock-parts",
      "trades-field-service-operations",
      "Truck Stock Parts And Materials",
      50,
      "Track truck stock, parts usage, materials, tools, restock needs, purchasing, and job-to-inventory evidence.",
      ["operate"],
    ),
    l2(
      "trades-quotes-contracts-billing",
      "trades-field-service-operations",
      "Quotes Contracts And Billing Readiness",
      60,
      "Prepare quotes, maintenance contracts, labour and materials billing, purchase orders, deposits, VAT/tax posture, and collections evidence.",
      ["consume", "operate", "integrate"],
    ),
    l2(
      "trades-safety-compliance-subcontractors",
      "trades-field-service-operations",
      "Safety Compliance And Subcontractors",
      70,
      "Manage site safety, PPE, certificates, insurance, subcontractors, waste disposal, and regulated trade obligations.",
      ["operate"],
    ),
  ],
};

const FABRIC_CARE_SERVICES: BusinessCapabilityPerspective = {
  perspectiveId: "fabric-care-services",
  label: "Fabric Care Services",
  source: "DPF fabric-care overlay informed by dry-cleaning POS, claim-ticket custody, plant/workroom flow, ready notifications, pickup routes, and garment-care operating patterns",
  capabilities: [
    l1(
      "fabric-care-operations",
      "Fabric Care Operations",
      100,
      "Operate garment and textile care across intake, claim tickets, plant/workroom processing, pickup and delivery, customer notices, and account billing readiness.",
      ["consume", "operate"],
    ),
    l2(
      "fabric-care-intake-claim-ticket",
      "fabric-care-operations",
      "Intake Claim Ticket And Tagging",
      10,
      "Capture customer, garment count, care instructions, stains, existing damage, special handling, and claim-ticket/tag evidence at drop-off or pickup.",
      ["consume", "operate"],
    ),
    l2(
      "fabric-care-plant-workroom-flow",
      "fabric-care-operations",
      "Plant Workroom And Route Flow",
      20,
      "Coordinate dry cleaning, laundry, pressing, alterations, commercial account work, and route handoffs through the plant or satellite-store network.",
      ["operate"],
    ),
    l2(
      "fabric-care-ready-promise-notices",
      "fabric-care-operations",
      "Ready Promise Notices And Exceptions",
      30,
      "Track promised-ready dates, send ready notices, escalate delays, and keep customer communication attached to the ticket.",
      ["integrate", "operate"],
    ),
    l2(
      "fabric-care-garment-custody-exceptions",
      "fabric-care-operations",
      "Garment Custody Exceptions",
      40,
      "Handle missing, damaged, mixed, delayed, or ambiguous garments as custody exceptions with manager visibility and resolution evidence.",
      ["operate"],
    ),
    l2(
      "fabric-care-supplies-equipment",
      "fabric-care-operations",
      "Supplies Equipment And Plant Readiness",
      50,
      "Track cleaning chemistry, tags, hangers, bags, equipment maintenance, and consumable purchasing that protect ready promises.",
      ["operate"],
    ),
    l2(
      "fabric-care-pos-account-billing",
      "fabric-care-operations",
      "POS Account And Billing Readiness",
      60,
      "Prepare point-of-sale payment, route delivery charges, recurring laundry plans, commercial account billing, and reconciliation evidence.",
      ["consume", "operate", "integrate"],
    ),
  ],
};

const BIAN_BANKING_V14: BusinessCapabilityPerspective = {
  perspectiveId: "bian-banking-v14",
  label: "Banking (BIAN v14)",
  source:
    "BIAN Service Landscape v14.0 Value Chain View — docs/Reference/bian/bian-v14-service-landscape.json (curated SMB engagement-layer subset; L1=Business Area, L2=Business Domain, L3=Service Domain per the BIAN/CSDM v7.6 projection pattern)",
  capabilities: [
    // ── L1: BIAN Business Area "Customers" ─────────────────────────────────
    l1("bian-customers", "Customers", 200, "BIAN Business Area: acquire, know, serve, and grow customer relationships.", ["consume", "operate"]),
    l2("bian-relationship-management", "bian-customers", "Relationship Management", 10, "BIAN Business Domain: develop and maintain customer relationships, insight, and credit standing.", ["consume", "operate"]),
    l3("bian-customer-relationship-management", "bian-relationship-management", "Customer Relationship Management", 10, "Develops and executes a customer plan to maintain and build a customer relationship.", ["consume", "operate"]),
    l3("bian-customer-credit-rating", "bian-relationship-management", "Customer Credit Rating", 20, "Maintains and administers the bank's credit assessment for customers based on consolidated internal data and optionally external credit agency reports.", ["operate"]),
    l3("bian-customer-behavior-insights", "bian-relationship-management", "Customer Behavior Insights", 30, "Applies behavioral analysis to customer event history to maintain a range of customer ratings/scores.", ["explore"]),
    l2("bian-customer-care", "bian-customers", "Customer Care", 20, "BIAN Business Domain: handle customer servicing requests, cases, and contact.", ["consume", "operate"]),
    l3("bian-customer-case", "bian-customer-care", "Customer Case", 10, "Handles the initiation, tracking, resolution and reporting on customer cases.", ["operate"]),
    l3("bian-servicing-order", "bian-customer-care", "Servicing Order", 20, "Handles the processing of a customer servicing request as a predefined procedure.", ["operate"]),
    l2("bian-sales", "bian-customers", "Sales", 30, "BIAN Business Domain: offers, campaigns, leads, and party onboarding.", ["explore", "consume"]),
    l3("bian-customer-offer", "bian-sales", "Customer Offer", 10, "Orchestrates the processing of a product offer for a new or established customer.", ["consume"]),
    l3("bian-lead-opportunity-management", "bian-sales", "Lead and Opportunity Management", 20, "Captures, classifies and tracks sales leads/opportunities with established clients.", ["explore"]),
    l3("bian-party-lifecycle-management", "bian-sales", "Party Lifecycle Management", 30, "Tracks the state of a party relationship with the bank from the initial checks made during establishment — the membership/onboarding anchor.", ["consume", "operate"]),
    l2("bian-party-reference", "bian-customers", "Party Reference", 40, "BIAN Business Domain: canonical party and location reference data.", ["operate"]),
    l3("bian-party-reference-data-directory", "bian-party-reference", "Party Reference Data Directory", 10, "Maintains party reference information covering general reference details for customers and counterparties.", ["operate"]),

    // ── L1: BIAN Business Area "Products" ──────────────────────────────────
    l1("bian-products", "Products", 210, "BIAN Business Area: the deposit, lending, and card products the institution offers.", ["consume", "operate"]),
    l2("bian-loans-and-deposits", "bian-products", "Loans and Deposits", 10, "BIAN Business Domain: deposit and lending product fulfillment.", ["consume", "operate"]),
    l3("bian-savings-account", "bian-loans-and-deposits", "Savings Account", 10, "Orchestrates a consumer savings account including payments, deposits, interest, and fees.", ["operate"]),
    l3("bian-term-deposit", "bian-loans-and-deposits", "Term Deposit", 20, "An interest bearing account into which a customer places a fixed amount of funds for a fixed term — certificates of deposit / share certificates.", ["operate"]),
    l3("bian-consumer-loan", "bian-loans-and-deposits", "Consumer Loan", 30, "Handles the fulfillment of a consumer loan product including set-up and scheduled processing.", ["operate"]),
    l3("bian-mortgage-loan", "bian-loans-and-deposits", "Mortgage Loan", 40, "Fulfillment of a loan product for the purpose of property purchase.", ["operate"]),
    l3("bian-corporate-loan", "bian-loans-and-deposits", "Corporate Loan", 50, "Handles the fulfillment of a corporate loan product for business customers.", ["operate"]),
    l3("bian-underwriting", "bian-loans-and-deposits", "Underwriting", 60, "Manages the underwriting decision process for products as appropriate, including many loan types.", ["operate"]),
    l2("bian-consumer-banking", "bian-products", "Consumer Banking", 20, "BIAN Business Domain: everyday consumer banking facilities.", ["consume", "operate"]),
    l3("bian-current-account", "bian-consumer-banking", "Current Account", 10, "Orchestrates a consumer checking/demand deposit account with its range of services and fees.", ["operate"]),
    l3("bian-payment-order-initiation", "bian-consumer-banking", "Payment Order Initiation", 20, "Provides a customer payment service capturing payer and payee details and key payment properties.", ["consume"]),
    l2("bian-cards", "bian-products", "Cards", 30, "BIAN Business Domain: card products and servicing.", ["consume", "operate"]),
    l3("bian-credit-card", "bian-cards", "Credit Card", 10, "Orchestrates the scheduled maintenance and transactional activities associated with credit card products.", ["operate"]),

    // ── L1: BIAN Business Area "Operations" ────────────────────────────────
    l1("bian-operations", "Operations", 220, "BIAN Business Area: product and account back-office operations.", ["operate"]),
    l2("bian-accounting-services", "bian-operations", "Accounting Services", 10, "BIAN Business Domain: position keeping, customer positions, and reconciliation.", ["operate"]),
    l3("bian-position-keeping", "bian-accounting-services", "Position Keeping", 10, "Maintains a log of monetary or value transactions and entitlements posted to product facilities.", ["operate"]),
    l3("bian-customer-position", "bian-accounting-services", "Customer Position", 20, "Maintains a consolidated financial position for a customer, combining details from all products.", ["operate"]),
    l3("bian-account-reconciliation", "bian-accounting-services", "Account Reconciliation", 30, "Handles account reconciliation tasks.", ["operate"]),

    // ── L1: BIAN Business Area "Finance And Risk Management" ───────────────
    l1("bian-finance-risk", "Finance And Risk Management", 230, "BIAN Business Area: regulatory compliance and credit/fraud risk posture — where jurisdiction-specific regulatory governance attaches (spec §9.4).", ["operate"]),
    l2("bian-compliance", "bian-finance-risk", "Compliance", 10, "BIAN Business Domain: interpret regulatory requirements, test adherence, and report — anchors the install's jurisdiction/charter posture.", ["operate"]),
    l3("bian-regulatory-compliance", "bian-compliance", "Regulatory Compliance", 10, "Interprets regulatory requirements, provides guidance, and defines and implements compliance processes.", ["operate"]),
    l3("bian-guideline-compliance", "bian-compliance", "Guideline Compliance", 20, "Develops and applies a portfolio of guideline compliance tests to confirm adherence to bank and regulatory guidelines.", ["operate"]),
    l3("bian-regulatory-reporting", "bian-compliance", "Regulatory Reporting", 30, "Administers and orchestrates the tasks required to meet the institution's regulatory reporting obligations.", ["operate"]),
    l2("bian-credit-risk", "bian-finance-risk", "Credit Risk", 20, "BIAN Business Domain: credit qualification and fraud response.", ["operate"]),
    l3("bian-credit-management", "bian-credit-risk", "Credit Management", 10, "Provides a bank-wide oversight function to qualify credit pricing for offered products and services.", ["operate"]),
    l3("bian-fraud-resolution", "bian-credit-risk", "Fraud Resolution", 20, "Sets up and processes a fraud case resulting from fraud behavior detected during production.", ["operate"]),
  ],
};

function categoryPerspective(template: CategoryCapabilityTemplate): BusinessCapabilityPerspective {
  return {
    perspectiveId: template.perspectiveId,
    label: template.label,
    source: template.source,
    capabilities: [
      l1(
        template.rootKey,
        template.rootName,
        template.rootSortOrder,
        template.rootDescription,
        template.rootValueStreams,
      ),
      ...template.lanes.map((lane, index) =>
        l2(
          lane.key,
          template.rootKey,
          lane.name,
          (index + 1) * 10,
          lane.description,
          lane.it4itValueStreams,
        ),
      ),
    ],
  };
}

export const CATEGORY_BUSINESS_CAPABILITY_PERSPECTIVES: Record<string, BusinessCapabilityPerspective> = {
  "asset-rental": categoryPerspective({
    perspectiveId: "asset-rental",
    label: "Asset Rental",
    source: "DPF asset-rental overlay informed by reservations, checkout/return custody, inspections, deposits, delivery, maintenance, and asset-pool readiness.",
    rootKey: "asset-rental-operations",
    rootName: "Asset Rental Operations",
    rootDescription: "Coordinate rentable inventory, booking windows, custody, readiness, delivery, damage, and revenue assurance.",
    rootSortOrder: 120,
    rootValueStreams: ["consume", "operate"],
    lanes: [
      { key: "rental-availability-reservations", name: "Availability And Reservations", description: "Maintain bookable asset calendars, holds, conflicts, quote requests, and reservation confirmations.", it4itValueStreams: ["consume"] },
      { key: "rental-checkout-return-inspection", name: "Checkout Return And Inspection", description: "Record custody transfer, condition, accessories, returns, damage notes, and redeploy readiness.", it4itValueStreams: ["operate"] },
      { key: "rental-maintenance-readiness", name: "Maintenance And Readiness", description: "Track cleaning, service, repairs, certification, charging, staging, and readiness blocks before the next rental.", it4itValueStreams: ["operate"] },
      { key: "rental-pricing-deposits-damage", name: "Pricing Deposits And Damage", description: "Manage rental rates, deposits, late fees, damage charges, waivers, refunds, and payment reconciliation.", it4itValueStreams: ["consume", "operate"] },
      { key: "rental-delivery-installation", name: "Delivery Installation And Pickup", description: "Plan delivery, setup, pickup, routing, customer notices, and crew handoffs for rental jobs.", it4itValueStreams: ["operate"] },
    ],
  }),
  "automotive-services": categoryPerspective({
    perspectiveId: "automotive-services",
    label: "Automotive Services",
    source: "DPF automotive-services overlay informed by appointment intake, diagnostics, bay capacity, parts, estimate approval, repair delivery, warranty, and customer follow-up.",
    rootKey: "automotive-service-operations",
    rootName: "Automotive Service Operations",
    rootDescription: "Run vehicle service from intake through estimate, technician work, parts readiness, delivery, and warranty follow-up.",
    rootSortOrder: 120,
    rootValueStreams: ["consume", "operate"],
    lanes: [
      { key: "automotive-appointment-diagnostics", name: "Appointment Intake And Diagnostics", description: "Capture vehicle, symptom, customer, inspection, and diagnostic context before technician work begins.", it4itValueStreams: ["consume"] },
      { key: "automotive-bay-technician-capacity", name: "Bay And Technician Capacity", description: "Schedule bays, technicians, mobile units, equipment, and promised completion windows.", it4itValueStreams: ["operate"] },
      { key: "automotive-parts-estimate-approval", name: "Parts Estimate And Approval", description: "Coordinate parts availability, estimate options, authorization, deposits, and change approvals.", it4itValueStreams: ["consume", "integrate"] },
      { key: "automotive-repair-delivery", name: "Repair Delivery And Quality", description: "Track work steps, inspection results, road tests, completion evidence, and vehicle release readiness.", it4itValueStreams: ["operate"] },
      { key: "automotive-customer-followup-warranty", name: "Customer Follow-Up And Warranty", description: "Handle repair status, recalls, recommendations, warranty claims, reviews, and repeat-service reminders.", it4itValueStreams: ["operate"] },
    ],
  }),
  "banking-financial-services": BIAN_BANKING_V14,
  "beauty-personal-care": BEAUTY_PERSONAL_CARE,
  "education-training": categoryPerspective({
    perspectiveId: "education-training",
    label: "Education And Training",
    source: "DPF education-training overlay informed by program catalog, enrollment, class scheduling, instructor capacity, learner progress, certification, and employer reporting.",
    rootKey: "education-training-operations",
    rootName: "Education And Training Operations",
    rootDescription: "Coordinate learning offers, enrollment, cohorts, instructors, learner progress, completion evidence, and reporting obligations.",
    rootSortOrder: 120,
    rootValueStreams: ["consume", "operate"],
    lanes: [
      { key: "education-program-catalog", name: "Program Catalog And Offers", description: "Maintain courses, classes, workshops, tuition, prerequisites, learning outcomes, and sellable program variants.", it4itValueStreams: ["explore", "consume"] },
      { key: "education-enrollment-scheduling", name: "Enrollment And Scheduling", description: "Manage inquiries, applications, registration, rosters, waitlists, sessions, rooms, and calendar changes.", it4itValueStreams: ["consume", "operate"] },
      { key: "education-learner-progress", name: "Learner Progress And Support", description: "Track attendance, assignments, milestones, accommodations, interventions, and learner communications.", it4itValueStreams: ["operate"] },
      { key: "education-instructor-capacity", name: "Instructor Capacity And Materials", description: "Coordinate instructors, lesson materials, equipment, substitute coverage, and delivery readiness.", it4itValueStreams: ["operate"] },
      { key: "education-certification-employer-reporting", name: "Certification And Reporting", description: "Prepare completion credentials, compliance records, employer reports, transcripts, and outcome evidence.", it4itValueStreams: ["operate"] },
    ],
  }),
  "fabric-care-services": FABRIC_CARE_SERVICES,
  "agriculture-ranching": categoryPerspective({
    perspectiveId: "agriculture-ranching",
    label: "Agriculture And Ranching",
    source: "DPF agriculture-ranching overlay grounded in seasonal land, crop, forage, livestock, working-animal, equipment, material, vendor, market, weather, and regulatory operating patterns.",
    rootKey: "agriculture-ranching-operations",
    rootName: "Agriculture And Ranching Operations",
    rootDescription: "Coordinate land-based production as interdependent biological, seasonal, geographic, equipment, labor, supplier, market, and compliance cycles.",
    rootSortOrder: 100,
    rootValueStreams: ["explore", "consume", "operate"],
    lanes: [
      { key: "agriculture-land-field-pasture-planning", name: "Land Field Pasture And Forage Planning", description: "Maintain property, field, pasture, soil, crop, hay, grazing, water, observation, and seasonal-work context with dated evidence.", it4itValueStreams: ["explore", "operate"] },
      { key: "agriculture-livestock-breeding-health", name: "Livestock Breeding Health And Movement", description: "Coordinate individual and herd identity, breeding, birth, care-plan, treatment, withdrawal, movement, welfare, and disposition records with qualified-professional authority.", it4itValueStreams: ["operate"] },
      { key: "agriculture-working-animal-readiness", name: "Working Animal Care And Readiness", description: "Track working-horse health, vaccination, dental, hoof and farrier, workload, rest, tack, restriction, handler, and appointment needs.", it4itValueStreams: ["operate"] },
      { key: "agriculture-equipment-implement-maintenance", name: "Equipment Implement And Maintenance Readiness", description: "Coordinate tractors, vehicles, machines, implements, compatibility, inspections, meter-based maintenance, defects, parts, fluids, dealers, and work-window readiness.", it4itValueStreams: ["operate"] },
      { key: "agriculture-material-lot-inventory", name: "Feed Seed Input Part And Lot Inventory", description: "Track quantities, lots, labels, storage, expiry, restrictions, reorder thresholds, reservations, and actual use for production materials and critical spares.", it4itValueStreams: ["operate"] },
      { key: "agriculture-vendor-outside-service", name: "Vendor Dealer And Outside Service Coordination", description: "Plan veterinarian, farrier, custom operator, applicator, hauler, laboratory, dealer, technician, parts, and supplier capacity against latest-safe dates and fallbacks.", it4itValueStreams: ["consume", "operate"] },
      { key: "agriculture-market-weather-decisions", name: "Market Weather And Sale Decision Intelligence", description: "Combine dated, like-for-like market reports, current observations, forecasts, seasonal outlooks, enterprise economics, and owner constraints into scenario-based decision briefs.", it4itValueStreams: ["explore", "consume"] },
      { key: "agriculture-regulation-license-exemption", name: "Regulation License Label And Exemption Control", description: "Retain authoritative labels, licenses, certifications, movement requirements, filings, agricultural exemptions, effective dates, qualifying facts, owners, and evidence by jurisdiction.", it4itValueStreams: ["operate"] },
    ],
  }),
  "fitness-recreation": categoryPerspective({
    perspectiveId: "fitness-recreation",
    label: "Fitness And Recreation",
    source: "DPF fitness-recreation overlay informed by memberships, class packs, session schedules, coach capacity, member progress, facility readiness, and retention marketing.",
    rootKey: "fitness-recreation-operations",
    rootName: "Fitness And Recreation Operations",
    rootDescription: "Run memberships, bookings, sessions, coaches, equipment, participation, facility readiness, and retention loops.",
    rootSortOrder: 120,
    rootValueStreams: ["consume", "operate"],
    lanes: [
      { key: "fitness-memberships-packages", name: "Memberships Packages And Access", description: "Manage member plans, passes, waivers, access status, freezes, renewals, and payment readiness.", it4itValueStreams: ["consume", "operate"] },
      { key: "fitness-class-session-schedule", name: "Class Session And Facility Schedule", description: "Coordinate classes, courts, spaces, instructors, waitlists, cancellations, and attendance capacity.", it4itValueStreams: ["operate"] },
      { key: "fitness-coach-member-progress", name: "Coach And Member Progress", description: "Track goals, assessments, plans, participation, coaching notes, and member follow-up.", it4itValueStreams: ["operate"] },
      { key: "fitness-facility-equipment-readiness", name: "Facility And Equipment Readiness", description: "Maintain rooms, equipment, cleaning, safety checks, supplies, and repair holds.", it4itValueStreams: ["operate"] },
      { key: "fitness-retention-local-marketing", name: "Retention And Local Marketing", description: "Coordinate offers, referrals, reviews, campaigns, inactive-member outreach, and community events.", it4itValueStreams: ["explore", "consume"] },
    ],
  }),
  "food-hospitality": categoryPerspective({
    perspectiveId: "food-hospitality",
    label: "Food And Hospitality",
    source: "DPF food-hospitality overlay informed by reservations/orders, service-period readiness, menu/prep, ingredients, staff coverage, guest communications, POS, and catering invoicing.",
    rootKey: "food-hospitality-operations",
    rootName: "Food And Hospitality Operations",
    rootDescription: "Run guest demand, menu availability, prep, production, staff coverage, service handoffs, order fulfillment, and follow-up.",
    rootSortOrder: 120,
    rootValueStreams: ["consume", "operate"],
    lanes: [
      { key: "food-service-period-readiness", name: "Service Period Readiness", description: "Coordinate reservations, orders, covers, tables, staff coverage, service windows, and exceptions before each service period.", it4itValueStreams: ["consume", "operate"] },
      { key: "food-menu-prep-inventory", name: "Menu Prep And Ingredient Readiness", description: "Track menu availability, prep lists, batches, allergens, substitutions, ingredient stock, and supplier gaps.", it4itValueStreams: ["operate"] },
      { key: "food-production-fulfillment", name: "Production And Fulfillment", description: "Coordinate kitchen, bakery, catering, packing, pickup, delivery, and handoff work against promised times.", it4itValueStreams: ["operate"] },
      { key: "food-guest-experience-followup", name: "Guest Experience And Follow-Up", description: "Handle guest messages, review responses, complaints, refunds, catering follow-up, and loyalty touches.", it4itValueStreams: ["consume", "operate"] },
      { key: "food-deposits-tickets-billing", name: "Deposits Tickets And Billing", description: "Manage deposits, tickets, event balances, no-show policy, POS settlement, catering invoices, and reconciliation evidence.", it4itValueStreams: ["consume", "operate", "integrate"] },
    ],
  }),
  "healthcare-wellness": categoryPerspective({
    perspectiveId: "healthcare-wellness",
    label: "Healthcare And Wellness",
    source: "DPF healthcare-wellness overlay informed by appointment intake, care readiness, patient communications, consent, regulated records, billing posture, and provider capacity.",
    rootKey: "healthcare-wellness-operations",
    rootName: "Healthcare And Wellness Operations",
    rootDescription: "Coordinate appointments, intake, provider readiness, patient communication, care evidence, consent, billing posture, and regulatory controls.",
    rootSortOrder: 120,
    rootValueStreams: ["consume", "operate"],
    lanes: [
      { key: "healthcare-appointment-intake", name: "Appointment Intake And Eligibility", description: "Capture patient details, reason for visit, eligibility posture, forms, referrals, and pre-visit requirements.", it4itValueStreams: ["consume", "integrate"] },
      { key: "healthcare-care-delivery-readiness", name: "Care Delivery Readiness", description: "Coordinate providers, rooms, equipment, tasks, orders, visit prep, and mobile-care readiness.", it4itValueStreams: ["operate"] },
      { key: "healthcare-patient-communications", name: "Patient Communications And Follow-Up", description: "Manage reminders, portal messages, care instructions, questions, recall outreach, and post-visit follow-up.", it4itValueStreams: ["consume", "operate"] },
      { key: "healthcare-records-consent-compliance", name: "Records Consent And Compliance", description: "Maintain consent, privacy, regulated records, disclosures, incident evidence, and retention obligations.", it4itValueStreams: ["operate"] },
      { key: "healthcare-billing-coverage-posture", name: "Billing And Coverage Posture", description: "Track self-pay, coverage facts, estimates, claims posture, invoices, payments, and reconciliation evidence.", it4itValueStreams: ["consume", "integrate"] },
    ],
  }),
  "hoa-property-management": categoryPerspective({
    perspectiveId: "hoa-property-management",
    label: "HOA And Property Management",
    source: "DPF HOA/property overlay informed by owner/resident requests, maintenance vendors, approvals, violations, dues, board work, and community communications.",
    rootKey: "property-governance-operations",
    rootName: "Property Governance Operations",
    rootDescription: "Coordinate property requests, vendors, board decisions, dues, violations, approvals, notices, and resident communications.",
    rootSortOrder: 120,
    rootValueStreams: ["consume", "operate"],
    lanes: [
      { key: "property-owner-tenant-requests", name: "Owner Resident And Tenant Requests", description: "Capture resident requests, questions, complaints, owner changes, portal messages, and service triage.", it4itValueStreams: ["consume", "operate"] },
      { key: "property-maintenance-vendor-work", name: "Maintenance And Vendor Work", description: "Coordinate work orders, vendor dispatch, inspections, bids, approvals, completion evidence, and resident notices.", it4itValueStreams: ["operate"] },
      { key: "property-violations-approvals", name: "Violations And Architectural Approvals", description: "Track violations, notices, hearings, approvals, documents, due dates, and resolution evidence.", it4itValueStreams: ["operate"] },
      { key: "property-dues-rent-finance", name: "Dues Rent And Finance", description: "Manage assessments, rent, fees, collections, deposits, vendor bills, budgets, and owner/accountant packets.", it4itValueStreams: ["consume", "operate"] },
      { key: "property-board-community-communications", name: "Board And Community Communications", description: "Prepare agendas, minutes, announcements, voting context, newsletters, and governed communication records.", it4itValueStreams: ["operate"] },
    ],
  }),
  "live-events-venues": categoryPerspective({
    perspectiveId: "live-events-venues",
    label: "Live Events And Venues",
    source: "DPF live-events/venues overlay informed by booking contracts, ticketing capacity, production readiness, staffing, guest communications, and event settlement.",
    rootKey: "events-venue-operations",
    rootName: "Events And Venue Operations",
    rootDescription: "Run event demand, booking calendars, capacity, ticketing, production readiness, staffing, guest communication, settlement, and post-event follow-up.",
    rootSortOrder: 120,
    rootValueStreams: ["consume", "operate"],
    lanes: [
      { key: "events-booking-contract-calendar", name: "Booking Contract And Calendar", description: "Coordinate event inquiries, holds, contracts, deposits, room calendars, technical needs, and change requests.", it4itValueStreams: ["consume", "operate"] },
      { key: "events-ticketing-capacity-sales", name: "Ticketing Capacity And Sales", description: "Manage ticket inventory, seating, guest lists, access, refunds, promotions, and sales channel reconciliation.", it4itValueStreams: ["consume", "integrate"] },
      { key: "events-production-staffing-readiness", name: "Production Staffing And Readiness", description: "Plan run-of-show, crew, vendors, equipment, catering, security, load-in, and readiness checks.", it4itValueStreams: ["operate"] },
      { key: "events-guest-communications", name: "Guest Communications And Service", description: "Send updates, handle inquiries, accessibility needs, incident reports, and on-site service exceptions.", it4itValueStreams: ["consume", "operate"] },
      { key: "events-settlement-post-event-followup", name: "Settlement And Post-Event Follow-Up", description: "Reconcile settlements, vendor bills, artist/promoter splits, damage, feedback, and repeat-booking outreach.", it4itValueStreams: ["operate"] },
    ],
  }),
  "manufacturing": categoryPerspective({
    perspectiveId: "manufacturing",
    label: "Manufacturing",
    source: "DPF manufacturing overlay informed by industrial-equipment OEM patterns: application engineering, engineered/build-to-order planning, bill-of-material and material readiness, serialized production execution, quality and acceptance, and delivery, spares, and lifecycle support.",
    rootKey: "manufacturing-operations",
    rootName: "Manufacturing Operations",
    rootDescription: "Run engineered and build-to-order production from application engineering through planning, material readiness, serialized build, quality acceptance, and installed-base lifecycle support.",
    rootSortOrder: 120,
    rootValueStreams: ["explore", "consume", "operate"],
    lanes: [
      { key: "manufacturing-application-product-engineering", name: "Application And Product Engineering", description: "Capture customer duty, environment, interface, and acceptance requirements; configure quotes; run design-for-manufacture review; and control prototype and new-product-introduction release.", it4itValueStreams: ["explore", "consume"] },
      { key: "manufacturing-order-production-planning", name: "Order And Production Planning", description: "Convert accepted orders into build plans, capacity and work-center scheduling, promised lead times, and change control across engineered and standard configurations.", it4itValueStreams: ["consume", "operate"] },
      { key: "manufacturing-material-bom-inventory", name: "Material BOM And Inventory Readiness", description: "Maintain bills of material, procurement, supplier lead time, lot and serial traceability, reorder thresholds, and staged material availability for release to production.", it4itValueStreams: ["operate", "integrate"] },
      { key: "manufacturing-production-execution", name: "Production Execution And Serialized Build", description: "Track work orders, routing steps, assembly, machine and labor readiness, as-built and serialized build records, and completion evidence.", it4itValueStreams: ["operate"] },
      { key: "manufacturing-quality-acceptance-compliance", name: "Quality Acceptance And Compliance", description: "Manage inspection plans, acceptance criteria, test results, nonconformance and corrective action, certifications, and traceable release-to-ship quality evidence.", it4itValueStreams: ["operate"] },
      { key: "manufacturing-delivery-spares-lifecycle", name: "Delivery Spares And Lifecycle Support", description: "Coordinate shipment, installation, commissioning, traceable spare parts, repair, retrofit, warranty, and lifecycle support for installed equipment.", it4itValueStreams: ["consume", "operate"] },
    ],
  }),
  "media-production": categoryPerspective({
    perspectiveId: "media-production",
    label: "Media Production",
    source: "DPF media-production overlay informed by creative briefs, crew/studio scheduling, production assets, review/approval, rights, delivery, and client billing.",
    rootKey: "media-production-operations",
    rootName: "Media Production Operations",
    rootDescription: "Coordinate briefs, shoots, crews, assets, post-production, approvals, delivery, rights, and project billing.",
    rootSortOrder: 120,
    rootValueStreams: ["consume", "operate"],
    lanes: [
      { key: "media-project-intake-brief", name: "Project Intake And Brief", description: "Capture client goals, scope, creative brief, budget, schedule, approvals, and production constraints.", it4itValueStreams: ["consume"] },
      { key: "media-crew-studio-schedule", name: "Crew Studio And Schedule", description: "Coordinate crew, talent, locations, studios, permits, equipment, call sheets, and day-of readiness.", it4itValueStreams: ["operate"] },
      { key: "media-production-asset-pipeline", name: "Production Asset Pipeline", description: "Track source files, versions, edits, storage, handoffs, approvals, and delivery package readiness.", it4itValueStreams: ["operate", "integrate"] },
      { key: "media-review-approval-delivery", name: "Review Approval And Delivery", description: "Manage client review rounds, feedback, signoff, release package, distribution, and archive evidence.", it4itValueStreams: ["consume", "operate"] },
      { key: "media-rights-billing-client-followup", name: "Rights Billing And Client Follow-Up", description: "Track usage rights, releases, invoice milestones, expenses, renewals, referrals, and account growth.", it4itValueStreams: ["operate"] },
    ],
  }),
  "moving-and-logistics": categoryPerspective({
    perspectiveId: "moving-and-logistics",
    label: "Moving And Logistics",
    source: "DPF moving/logistics overlay informed by quoting, routes, dispatch, crew/vehicle capacity, load custody, proof, carrier cutoffs, claims, and billing readiness.",
    rootKey: "logistics-moving-operations",
    rootName: "Moving And Logistics Operations",
    rootDescription: "Coordinate quote-to-delivery work across route planning, dispatch, crews, vehicles, custody, exceptions, claims, and billing.",
    rootSortOrder: 120,
    rootValueStreams: ["consume", "operate"],
    lanes: [
      { key: "logistics-booking-quote-route", name: "Booking Quote And Route", description: "Capture shipment, move, or delivery demand; estimate scope; reserve dates; and plan route windows.", it4itValueStreams: ["consume"] },
      { key: "logistics-dispatch-crew-vehicle", name: "Dispatch Crew And Vehicle", description: "Assign drivers, crews, vehicles, equipment, credentials, route stops, and day-of exceptions.", it4itValueStreams: ["operate"] },
      { key: "logistics-load-custody-proof", name: "Load Custody And Proof", description: "Track pickup, inventory, condition, chain of custody, delivery proof, signatures, photos, and exceptions.", it4itValueStreams: ["operate"] },
      { key: "logistics-carrier-cutoff-exceptions", name: "Carrier Cutoffs And Exceptions", description: "Manage carriers, appointments, dock times, cutoffs, delays, reschedules, and customer notifications.", it4itValueStreams: ["integrate", "operate"] },
      { key: "logistics-claims-billing-readiness", name: "Claims And Billing Readiness", description: "Handle damage claims, accessorials, deposits, balances, invoices, refunds, and reconciliation evidence.", it4itValueStreams: ["operate"] },
    ],
  }),
  "nonprofit-community": categoryPerspective({
    perspectiveId: "nonprofit-community",
    label: "Nonprofit And Community",
    source: "DPF nonprofit/community overlay informed by programs, donors, members, volunteers, grants, impact evidence, compliance, and community communications.",
    rootKey: "nonprofit-community-operations",
    rootName: "Nonprofit And Community Operations",
    rootDescription: "Coordinate programs, constituents, donors, members, volunteers, grants, impact reporting, compliance, and communications.",
    rootSortOrder: 120,
    rootValueStreams: ["consume", "operate"],
    lanes: [
      { key: "nonprofit-program-service-delivery", name: "Program And Service Delivery", description: "Run programs, services, eligibility, attendance, case notes, resource distribution, and constituent outcomes.", it4itValueStreams: ["operate"] },
      { key: "nonprofit-donor-member-relationships", name: "Donor Member And Constituent Relationships", description: "Manage donors, members, supporters, households, pledges, renewals, receipts, and stewardship touches.", it4itValueStreams: ["consume", "operate"] },
      { key: "nonprofit-volunteer-coordination", name: "Volunteer Coordination", description: "Coordinate volunteer roles, availability, onboarding, shifts, checks, assignments, and recognition.", it4itValueStreams: ["operate"] },
      { key: "nonprofit-grants-fundraising", name: "Grants And Fundraising", description: "Track campaigns, appeals, events, grants, deadlines, restrictions, budgets, and funder communications.", it4itValueStreams: ["explore", "consume"] },
      { key: "nonprofit-impact-compliance-reporting", name: "Impact Compliance And Reporting", description: "Prepare impact metrics, board packets, donor reports, grant evidence, filings, and audit-ready records.", it4itValueStreams: ["operate"] },
    ],
  }),
  "pet-services": categoryPerspective({
    perspectiveId: "pet-services",
    label: "Pet Services",
    source: "DPF pet-services overlay informed by booking, pet intake, vaccination posture, care notes, routes/boarding capacity, supplies, client communications, and follow-up.",
    rootKey: "pet-services-operations",
    rootName: "Pet Services Operations",
    rootDescription: "Run pet bookings, intake, care delivery, capacity, supplies, compliance, client communication, and follow-up.",
    rootSortOrder: 120,
    rootValueStreams: ["consume", "operate"],
    lanes: [
      { key: "pet-booking-care-intake", name: "Booking And Care Intake", description: "Capture pet, owner, service, temperament, medical notes, vaccination posture, and booking constraints.", it4itValueStreams: ["consume"] },
      { key: "pet-care-delivery-notes", name: "Care Delivery And Notes", description: "Track grooming, walking, boarding, veterinary, training, or daycare services with photos, notes, and exceptions.", it4itValueStreams: ["operate"] },
      { key: "pet-route-boarding-capacity", name: "Route Boarding And Capacity", description: "Coordinate routes, kennels, rooms, staff coverage, pickup windows, drop-off windows, and overbooking risk.", it4itValueStreams: ["operate"] },
      { key: "pet-client-communications", name: "Client Communications And Follow-Up", description: "Send reminders, status updates, post-service notes, review requests, recommendations, and rebooking prompts.", it4itValueStreams: ["consume", "operate"] },
      { key: "pet-supplies-vaccination-compliance", name: "Supplies Vaccination And Compliance", description: "Track supplies, medications, vaccine requirements, consent, licenses, incident evidence, and facility readiness.", it4itValueStreams: ["operate"] },
    ],
  }),
  "professional-services": categoryPerspective({
    perspectiveId: "professional-services",
    label: "Professional Services",
    source: "DPF professional-services overlay informed by client intake, engagement scoping, delivery work, decisions/deliverables, time/billing, pipeline, and relationship management.",
    rootKey: "professional-services-operations",
    rootName: "Professional Services Operations",
    rootDescription: "Coordinate client acquisition, scoping, engagements, deliverables, expertise, time, billing, and account growth.",
    rootSortOrder: 120,
    rootValueStreams: ["explore", "consume", "operate"],
    lanes: [
      { key: "professional-client-intake-scoping", name: "Client Intake And Scoping", description: "Capture client needs, fit, scope, proposals, statements of work, retainers, and authority to proceed.", it4itValueStreams: ["explore", "consume"] },
      { key: "professional-engagement-delivery", name: "Engagement Delivery", description: "Coordinate project tasks, advisory work, milestones, meetings, decision records, and delivery evidence.", it4itValueStreams: ["operate"] },
      { key: "professional-decision-deliverable-review", name: "Decisions Deliverables And Review", description: "Manage drafts, reviews, approvals, recommendations, deliverable packages, and client acceptance.", it4itValueStreams: ["operate"] },
      { key: "professional-time-billing-readiness", name: "Time Billing And Readiness", description: "Track time, expenses, retainers, milestones, invoices, write-offs, and accountant-ready reconciliation context.", it4itValueStreams: ["operate", "integrate"] },
      { key: "professional-relationship-pipeline", name: "Relationship And Pipeline", description: "Maintain referrals, prospects, renewals, expansion opportunities, client health, and follow-up cadence.", it4itValueStreams: ["explore", "consume"] },
    ],
  }),
  "public-sector": categoryPerspective({
    perspectiveId: "public-sector",
    label: "Public Sector And Civic",
    source: "DPF public-sector overlay informed by service requests, cases/permits, meetings, records, transparency, field crews, assets, and compliance evidence.",
    rootKey: "public-sector-service-operations",
    rootName: "Public Sector Service Operations",
    rootDescription: "Coordinate civic service requests, cases, permits, meetings, public records, field work, obligations, and transparency evidence.",
    rootSortOrder: 120,
    rootValueStreams: ["consume", "operate"],
    lanes: [
      { key: "public-service-request-intake", name: "Service Request Intake", description: "Receive constituent requests, complaints, questions, reports, attachments, location context, and routing signals.", it4itValueStreams: ["consume"] },
      { key: "public-case-permit-workflow", name: "Case Permit And Workflow", description: "Track permits, cases, inspections, decisions, approvals, due dates, fees, and status communications.", it4itValueStreams: ["operate"] },
      { key: "public-meeting-agenda-records", name: "Meetings Agendas And Records", description: "Prepare agendas, packets, minutes, actions, notices, records, and public-facing decision evidence.", it4itValueStreams: ["operate"] },
      { key: "public-compliance-transparency", name: "Compliance And Transparency", description: "Maintain obligations, public records posture, audit evidence, accessibility, retention, and reporting.", it4itValueStreams: ["operate"] },
      { key: "public-field-crew-asset-readiness", name: "Field Crew And Asset Readiness", description: "Coordinate crews, facilities, vehicles, assets, work orders, inspections, and incident response readiness.", it4itValueStreams: ["operate"] },
    ],
  }),
  "real-estate-construction": categoryPerspective({
    perspectiveId: "real-estate-construction",
    label: "Real Estate And Construction",
    source: "DPF real-estate/construction overlay informed by lead estimates, contracts, project schedules, sites, crews/subcontractors, materials, inspections, compliance, and handover.",
    rootKey: "construction-property-operations",
    rootName: "Construction And Property Operations",
    rootDescription: "Coordinate property, project, site, crew, subcontractor, materials, compliance, customer, and handover work.",
    rootSortOrder: 120,
    rootValueStreams: ["consume", "operate"],
    lanes: [
      { key: "construction-lead-estimate-contract", name: "Lead Estimate And Contract", description: "Manage leads, site visits, estimates, options, contracts, deposits, selections, and change authority.", it4itValueStreams: ["explore", "consume"] },
      { key: "construction-project-schedule", name: "Project Schedule And Milestones", description: "Coordinate phases, milestones, calendars, dependencies, inspections, client updates, and schedule risk.", it4itValueStreams: ["operate"] },
      { key: "construction-site-crew-subcontractors", name: "Site Crew And Subcontractors", description: "Assign crews, trades, subcontractors, credentials, daily logs, safety checks, and issue resolution.", it4itValueStreams: ["operate"] },
      { key: "construction-materials-equipment", name: "Materials Equipment And Procurement", description: "Track materials, purchase orders, rentals, equipment, deliveries, backorders, and inventory at job sites.", it4itValueStreams: ["operate", "integrate"] },
      { key: "construction-inspection-compliance-handover", name: "Inspection Compliance And Handover", description: "Manage permits, inspections, punch lists, warranties, closeout documents, draw evidence, and handover.", it4itValueStreams: ["operate"] },
    ],
  }),
  "retail-goods": categoryPerspective({
    perspectiveId: "retail-goods",
    label: "Retail Goods",
    source: "DPF retail-goods overlay informed by product catalog, pricing, inventory, orders, fulfillment, returns, POS, marketplaces, and customer service.",
    rootKey: "retail-commerce-operations",
    rootName: "Retail Commerce Operations",
    rootDescription: "Run sellable goods across catalog, inventory, orders, fulfillment, customer support, returns, channels, and reconciliation.",
    rootSortOrder: 120,
    rootValueStreams: ["consume", "operate"],
    lanes: [
      { key: "retail-catalog-pricing", name: "Catalog Pricing And Merchandising", description: "Maintain products, variants, bundles, prices, promotions, availability, photos, and channel listings.", it4itValueStreams: ["explore", "consume"] },
      { key: "retail-orders-fulfillment", name: "Orders And Fulfillment", description: "Coordinate carts, orders, pickup, delivery, shipping, substitutions, customer notices, and promised dates.", it4itValueStreams: ["consume", "operate"] },
      { key: "retail-inventory-replenishment", name: "Inventory And Replenishment", description: "Track stock, purchase needs, receiving, transfers, cycle counts, reorder points, and shrink risk.", it4itValueStreams: ["operate"] },
      { key: "retail-customer-service-returns", name: "Customer Service Returns And Exchanges", description: "Handle inquiries, returns, exchanges, refunds, complaints, repairs, and post-purchase follow-up.", it4itValueStreams: ["operate"] },
      { key: "retail-pos-marketplace-reconciliation", name: "POS Marketplace And Reconciliation", description: "Connect POS, ecommerce, marketplace, payment, fee, tax, and payout evidence for finance review.", it4itValueStreams: ["integrate", "operate"] },
    ],
  }),
  "security-services": categoryPerspective({
    perspectiveId: "security-services",
    label: "Security Services",
    source: "DPF security-services overlay informed by site coverage, guard schedules, credentials, patrol evidence, incidents, client communications, compliance, and equipment readiness.",
    rootKey: "security-service-operations",
    rootName: "Security Service Operations",
    rootDescription: "Coordinate contracted coverage, guards, credentials, patrols, incidents, evidence, client notices, compliance, and equipment.",
    rootSortOrder: 120,
    rootValueStreams: ["consume", "operate"],
    lanes: [
      { key: "security-contract-site-coverage", name: "Contract Site And Coverage", description: "Maintain sites, posts, service levels, patrol instructions, coverage windows, and client obligations.", it4itValueStreams: ["consume", "operate"] },
      { key: "security-guard-schedule-credential", name: "Guard Schedule And Credentials", description: "Coordinate staff availability, credentials, licenses, training, uniform readiness, and shift assignments.", it4itValueStreams: ["operate"] },
      { key: "security-incident-patrol-evidence", name: "Incident Patrol And Evidence", description: "Track patrol checkpoints, incidents, photos, reports, escalation, response, and evidence packets.", it4itValueStreams: ["operate"] },
      { key: "security-client-communications", name: "Client Communications And Exceptions", description: "Send shift updates, incident notices, staffing exceptions, recommendations, and account follow-up.", it4itValueStreams: ["consume", "operate"] },
      { key: "security-compliance-equipment-readiness", name: "Compliance And Equipment Readiness", description: "Maintain licenses, policies, radios, cameras, vehicles, keys, access devices, and audit evidence.", it4itValueStreams: ["operate"] },
    ],
  }),
  "software-platform": categoryPerspective({
    perspectiveId: "software-platform",
    label: "Software Platform",
    source: "DPF software-platform overlay informed by customer success, support, release/change governance, runtime health, incidents, roadmap, billing, and integration readiness.",
    rootKey: "software-platform-operations",
    rootName: "Software Platform Operations",
    rootDescription: "Operate a software business across customer success, product, support, runtime health, releases, billing, and integration readiness.",
    rootSortOrder: 120,
    rootValueStreams: ["explore", "consume", "operate"],
    lanes: [
      { key: "software-customer-success-support", name: "Customer Success And Support", description: "Manage onboarding, support cases, customer health, adoption, requests, escalations, and renewals.", it4itValueStreams: ["consume", "operate"] },
      { key: "software-release-change-governance", name: "Release And Change Governance", description: "Coordinate releases, change risk, approvals, notes, rollout evidence, and rollback posture.", it4itValueStreams: ["operate"] },
      { key: "software-runtime-incident-health", name: "Runtime Health And Incidents", description: "Monitor availability, incidents, observability, security events, dependencies, and customer impact.", it4itValueStreams: ["operate", "integrate"] },
      { key: "software-product-backlog-roadmap", name: "Product Backlog And Roadmap", description: "Prioritize roadmap, backlog, discovery, adoption evidence, commercial signals, and delivery investment.", it4itValueStreams: ["explore", "evaluate"] },
      { key: "software-billing-integration-readiness", name: "Billing And Integration Readiness", description: "Track subscriptions, usage, entitlements, payment providers, invoices, tax posture, and integration health.", it4itValueStreams: ["consume", "integrate"] },
    ],
  }),
  "trades-maintenance": TRADES_MAINTENANCE,
  "warehousing-fulfilment": categoryPerspective({
    perspectiveId: "warehousing-fulfilment",
    label: "Warehousing And Fulfilment",
    source: "DPF warehousing/fulfilment overlay informed by inbound receiving, inventory accuracy, slotting, pick-pack-ship, docks, carrier cutoffs, client billing, and exceptions.",
    rootKey: "warehouse-fulfilment-operations",
    rootName: "Warehouse And Fulfilment Operations",
    rootDescription: "Coordinate receiving, inventory custody, storage, pick-pack-ship work, dock flow, carrier exceptions, and client billing.",
    rootSortOrder: 120,
    rootValueStreams: ["consume", "operate"],
    lanes: [
      { key: "warehouse-inbound-receiving", name: "Inbound Receiving And Putaway", description: "Track appointments, ASN context, receiving, inspection, putaway, discrepancies, and supplier/customer notices.", it4itValueStreams: ["consume", "operate"] },
      { key: "warehouse-inventory-accuracy-slotting", name: "Inventory Accuracy And Slotting", description: "Maintain stock counts, locations, lot/serial facts, replenishment, cycle counts, and storage rules.", it4itValueStreams: ["operate"] },
      { key: "warehouse-pick-pack-ship", name: "Pick Pack And Ship", description: "Coordinate waves, picks, packing, labels, manifests, shipping, handoff evidence, and promised cutoffs.", it4itValueStreams: ["operate", "integrate"] },
      { key: "warehouse-dock-carrier-cutoff", name: "Dock Carrier And Cutoff Management", description: "Manage dock doors, carrier appointments, freight exceptions, late loads, holds, and customer updates.", it4itValueStreams: ["operate"] },
      { key: "warehouse-client-billing-exceptions", name: "Client Billing And Exceptions", description: "Track storage fees, handling charges, SLA exceptions, claims, credits, and reconciliation evidence.", it4itValueStreams: ["operate"] },
    ],
  }),
};

export const COVERED_BUSINESS_CAPABILITY_CATEGORIES = Object.freeze(
  Object.keys(CATEGORY_BUSINESS_CAPABILITY_PERSPECTIVES).sort(),
);

function l1(
  key: string,
  name: string,
  sortOrder: number,
  description: string,
  it4itValueStreams: string[],
): BusinessCapabilitySeedDefinition {
  return {
    key,
    name,
    description,
    level: 1,
    sortOrder,
    currentMaturity: 1,
    targetMaturity: 3,
    it4itValueStreams,
  };
}

function l2(
  key: string,
  parentKey: string,
  name: string,
  sortOrder: number,
  description: string,
  it4itValueStreams: string[],
): BusinessCapabilitySeedDefinition {
  return {
    key,
    parentKey,
    name,
    description,
    level: 2,
    sortOrder,
    currentMaturity: 1,
    targetMaturity: 3,
    it4itValueStreams,
  };
}

function l3(
  key: string,
  parentKey: string,
  name: string,
  sortOrder: number,
  description: string,
  it4itValueStreams: string[],
): BusinessCapabilitySeedDefinition {
  return {
    key,
    parentKey,
    name,
    description,
    level: 3,
    sortOrder,
    currentMaturity: 1,
    targetMaturity: 3,
    it4itValueStreams,
  };
}
