// mac-oui.ts
//
// Resolve a MAC address to its manufacturer via the IEEE OUI registry.
//
// Why this exists: nothing in the core discovery path resolved a MAC to a vendor.
// The vendors that appeared on the live install all came from the UniFi
// controller's OWN lookup, handed to us per-client in its API response. Anything
// the controller did not supply stayed unidentified — including every UniFi
// DEVICE, because the device endpoint returns no vendor field. Four access
// points, a gateway and a switch sat permanently unidentified as a result
// (BI-9632B15B), each asking an operator to name hardware whose MAC states the
// manufacturer outright.
//
// Depending on a vendor's API to volunteer the manufacturer is the fragile part.
// The OUI is on the wire.
//
// This module is PURE — callers supply the prefix→vendor map. `discovery-sync`
// loads it from the `MacVendorOui` table inside its transaction; tests pass a
// literal. That keeps `deriveInventoryEnrichment` untouched: it already reads
// `properties.vendor`, so a resolved vendor arrives by exactly the same route the
// controller's own value does today.

/** A locally-administered MAC has bit 0x02 set in its first octet. */
const LOCALLY_ADMINISTERED_BIT = 0x02;

/**
 * Normalize any common MAC rendering to an upper-case 12-hex-digit string.
 * Accepts `aa:bb:cc:dd:ee:ff`, `AA-BB-CC-DD-EE-FF`, `aabb.ccdd.eeff`, bare hex.
 * Returns null when the input is not 48 bits of hex.
 */
export function normalizeMac(raw: string | null | undefined): string | null {
  if (!raw) return null;
  const hex = raw.replace(/[^0-9a-fA-F]/g, "").toUpperCase();
  return hex.length === 12 ? hex : null;
}

/**
 * True when the MAC is locally administered (randomised) rather than burned in.
 *
 * These carry NO OUI by construction — the address was generated by the device,
 * not assigned by IEEE — so a lookup miss is the correct and permanent answer,
 * not a gap in the registry. On the live install every ARP host swept was of this
 * kind: 0 of 119 resolved, against 65 of 65 burned-in ones. Callers use this to
 * tell "we cannot know" apart from "we do not know yet" (BI-A3D12F85).
 */
export function isLocallyAdministered(mac: string | null | undefined): boolean {
  const normalized = normalizeMac(mac);
  if (!normalized) return false;
  return (Number.parseInt(normalized.slice(0, 2), 16) & LOCALLY_ADMINISTERED_BIT) !== 0;
}

/** The 24-bit OUI prefix of a MAC, or null when the MAC is unusable. */
export function ouiPrefix(mac: string | null | undefined): string | null {
  const normalized = normalizeMac(mac);
  return normalized ? normalized.slice(0, 6) : null;
}

export type MacVendorResolution = {
  vendor: string | null;
  /** Why there is no vendor — so callers can report accurately rather than guess. */
  reason: "resolved" | "randomised-mac" | "unknown-oui" | "invalid-mac";
};

/**
 * Resolve one MAC against a prefix→vendor map.
 *
 * Distinguishes the three ways a lookup can come back empty, because they mean
 * different things to the quality detector: a randomised MAC is unresolvable
 * forever, an unknown OUI may just need a refreshed registry, and an invalid MAC
 * is a collector bug.
 */
export function resolveMacVendor(
  mac: string | null | undefined,
  vendorsByOui: ReadonlyMap<string, string>,
): MacVendorResolution {
  const normalized = normalizeMac(mac);
  if (!normalized) return { vendor: null, reason: "invalid-mac" };
  if (isLocallyAdministered(normalized)) return { vendor: null, reason: "randomised-mac" };

  const vendor = vendorsByOui.get(normalized.slice(0, 6));
  return vendor
    ? { vendor, reason: "resolved" }
    : { vendor: null, reason: "unknown-oui" };
}

/**
 * Parse the seeded TSV (`<OUI>\t<vendor>` per line) into rows.
 *
 * Tolerant of blank lines, comments and stray whitespace so a registry refresh
 * dropped in from IEEE does not need hand-cleaning. Malformed lines are skipped
 * rather than thrown on — one bad row in 39k must not fail a seed.
 */
export function parseOuiRegistry(tsv: string): Array<{ oui: string; vendor: string }> {
  const rows: Array<{ oui: string; vendor: string }> = [];
  for (const line of tsv.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;

    const tab = trimmed.indexOf("\t");
    if (tab < 0) continue;

    const oui = trimmed.slice(0, tab).replace(/[^0-9a-fA-F]/g, "").toUpperCase();
    const vendor = trimmed.slice(tab + 1).trim();
    if (oui.length !== 6 || !vendor) continue;

    rows.push({ oui, vendor });
  }
  return rows;
}
