// BET-5 (BI-A1E864A5): one-time, idempotent copy of the live Neo4j graph into the Postgres
// graph mirror (graph_node / graph_edge). Runs during self-upgrade BEFORE Neo4j is removed
// (ordering per BI-922EBB99). Safe to re-run: if the mirror already holds InfraCI nodes the
// copy is skipped, and every insert uses ON CONFLICT DO NOTHING.
//
// Scope: every node with a resolvable business key — coalesce(productId, ciId, nodeId, slug)
// — plus every edge whose BOTH endpoints resolve. This captures the infra / EA / product /
// portfolio / taxonomy / document graph. InfraCI nodes have NO Postgres source of truth, so
// this backfill is the ONLY thing that preserves them across the cutover. Code-graph nodes
// (CodeFile / CodeSymbol / CodeRoute / …) are intentionally NOT copied here — they are a pure
// projection of the repository and are regenerated by the code-graph reconcile after cutover,
// so excluding them loses no authoritative data.

import neo4j from "neo4j-driver";
import { prisma } from "./client";
import { neo4jSession } from "./neo4j";

const KEY = "coalesce(n.productId, n.ciId, n.nodeId, n.slug)";
const SRC = "coalesce(a.productId, a.ciId, a.nodeId, a.slug)";
const DST = "coalesce(b.productId, b.ciId, b.nodeId, b.slug)";

/** Convert a Neo4j property value into a JSON-safe value (Integer→number, temporal→ISO string). */
function neo4jValueToJson(v: unknown): unknown {
  if (v === null || v === undefined) return null;
  if (neo4j.isInt(v)) return (v as { toNumber: () => number }).toNumber();
  if (Array.isArray(v)) return v.map(neo4jValueToJson);
  if (typeof v === "object") {
    // Temporal / spatial types are class instances with a meaningful toString().
    const ctor = (v as { constructor?: { name?: string } }).constructor;
    if (ctor && ctor.name && ctor.name !== "Object") {
      return String(v);
    }
    const out: Record<string, unknown> = {};
    for (const [k, val] of Object.entries(v)) out[k] = neo4jValueToJson(val);
    return out;
  }
  return v;
}

function neo4jPropsToJson(props: unknown): Record<string, unknown> {
  const j = neo4jValueToJson(props);
  return j && typeof j === "object" && !Array.isArray(j)
    ? (j as Record<string, unknown>)
    : {};
}

export async function backfillNeo4jToPgGraph(): Promise<{
  nodes: number;
  edges: number;
  skipped: boolean;
}> {
  // Skip if the mirror already holds InfraCI nodes (the non-regenerable payload).
  const existing = (await prisma.$queryRawUnsafe(
    `SELECT count(*)::int AS n FROM graph_node WHERE 'InfraCI' = ANY(labels)`,
  )) as Array<{ n: number }>;
  if ((existing[0]?.n ?? 0) > 0) return { nodes: 0, edges: 0, skipped: true };

  const session = neo4jSession();
  let nodes: Array<{ key: string; labels: string[]; props: Record<string, unknown> }>;
  let edges: Array<{ src: string; dst: string; rel: string; props: Record<string, unknown> }>;
  try {
    const nodeRes = await session.run(
      `MATCH (n) WITH n, ${KEY} AS k WHERE k IS NOT NULL
       RETURN k AS key, labels(n) AS labels, properties(n) AS props`,
    );
    nodes = nodeRes.records.map((r) => ({
      key: r.get("key") as string,
      labels: (r.get("labels") as string[]) ?? [],
      props: neo4jPropsToJson(r.get("props")),
    }));
    const edgeRes = await session.run(
      `MATCH (a)-[r]->(b) WITH a, r, b, ${SRC} AS sk, ${DST} AS dk
       WHERE sk IS NOT NULL AND dk IS NOT NULL
       RETURN sk AS src, dk AS dst, type(r) AS rel, properties(r) AS props`,
    );
    edges = edgeRes.records.map((r) => ({
      src: r.get("src") as string,
      dst: r.get("dst") as string,
      rel: r.get("rel") as string,
      props: neo4jPropsToJson(r.get("props")),
    }));
  } finally {
    await session.close();
  }

  // Dedup nodes by key (Neo4j may have multiple nodes coalescing to the same key).
  const seen = new Set<string>();
  let nodeCount = 0;
  for (const n of nodes) {
    if (seen.has(n.key)) continue;
    seen.add(n.key);
    await prisma.$executeRawUnsafe(
      `INSERT INTO graph_node (key, labels, props)
       VALUES ($1, $2::text[], $3::jsonb)
       ON CONFLICT (key) DO NOTHING`,
      n.key,
      n.labels,
      JSON.stringify(n.props),
    );
    nodeCount++;
  }
  let edgeCount = 0;
  for (const e of edges) {
    await prisma.$executeRawUnsafe(
      `INSERT INTO graph_edge (src_key, dst_key, rel_type, props)
       VALUES ($1, $2, $3, $4::jsonb)
       ON CONFLICT (src_key, dst_key, rel_type) DO NOTHING`,
      e.src,
      e.dst,
      e.rel,
      JSON.stringify(e.props),
    );
    edgeCount++;
  }
  return { nodes: nodeCount, edges: edgeCount, skipped: false };
}
