// packages/db/src/sync-capabilities.ts
// Reads platform tool metadata from platform-tools-snapshot.json and upserts into
// PlatformCapability table. Idempotent: safe to run on every deploy.
//
// The snapshot is generated by scripts/generate-tools-snapshot.js at build time
// from apps/web/lib/mcp-tools.ts. It contains name, description, and metadata flags
// for each platform tool.

import * as crypto from "crypto";
import { readFileSync } from "fs";
import { join } from "path";
import type { PrismaClient } from "../generated/client/client";
import { Prisma } from "../generated/client/client";

// ─── Types ────────────────────────────────────────────────────────────────────

type BuildPhaseTag = "ideate" | "plan" | "build" | "review" | "ship";

interface ToolSnapshot {
  name: string;
  description: string;
  sideEffect: boolean;
  requiresExternalAccess: boolean;
  buildPhases: BuildPhaseTag[] | null;
}

export interface RuntimeCapabilitySeed {
  capabilityId: string;
  name: string;
  description: string;
  state: string;
  manifest: Record<string, unknown>;
}

export const RUNTIME_CAPABILITY_IDS = [
  "runtime:core", "runtime:build", "runtime:browser-automation",
  "runtime:durable-automation", "runtime:local-speech",
  "runtime:deep-observability", "runtime:adp-integration",
  "runtime:development", "runtime:external-ai",
] as const;

// ─── Helpers ─────────────────────────────────────────────────────────────────

function computeDefinitionHash(tool: ToolSnapshot): string {
  const payload = JSON.stringify({
    name: tool.name,
    description: tool.description,
  });
  return crypto.createHash("sha256").update(payload).digest("hex").slice(0, 16);
}

type RiskClass = "critical" | "elevated" | "standard";
type AuditClass = "ledger" | "journal" | "metrics_only";

function deriveRiskClass(tool: ToolSnapshot): RiskClass {
  if (tool.sideEffect && tool.requiresExternalAccess) return "critical";
  if (tool.sideEffect || tool.requiresExternalAccess) return "elevated";
  return "standard";
}

function deriveAuditClass(tool: ToolSnapshot): AuditClass {
  if (tool.sideEffect) return "ledger";
  if (tool.requiresExternalAccess) return "journal";
  return "metrics_only";
}

// ─── Snapshot loader ─────────────────────────────────────────────────────────

function loadToolsSnapshot(): ToolSnapshot[] {
  const snapshotPath = join(__dirname, "platform-tools-snapshot.json");
  const raw = readFileSync(snapshotPath, "utf8");
  return JSON.parse(raw) as ToolSnapshot[];
}

export function validateRuntimeCapabilitySeeds(parsed: unknown): RuntimeCapabilitySeed[] {
  if (!parsed || typeof parsed !== "object") throw new Error("Invalid runtime capability seed");
  const seed = parsed as { version?: unknown; capabilities?: unknown };
  if (seed.version !== 1 || !Array.isArray(seed.capabilities)) throw new Error("Unsupported runtime capability seed");
  const capabilities = seed.capabilities as RuntimeCapabilitySeed[];
  const ids = capabilities.map((capability) => capability?.capabilityId);
  if (JSON.stringify(ids) !== JSON.stringify(RUNTIME_CAPABILITY_IDS)) throw new Error("Runtime capability seed identifiers do not match the canonical inventory");
  const idSet = new Set(ids);
  const allowedStates = new Set(["active", "disabled"]);
  const allowedActivationPolicies = new Set(["always", "operator-controlled", "lifecycle-profile", "provider-configuration"]);
  for (const capability of capabilities) {
    if (!capability.name?.trim() || !capability.description?.trim()) throw new Error(`invalid_runtime_capability:${capability.capabilityId}`);
    if (!allowedStates.has(capability.state)) throw new Error(`invalid_runtime_state:${capability.capabilityId}`);
    const runtime = capability.manifest?.runtime;
    if (!runtime || typeof runtime !== "object" || Array.isArray(runtime)) throw new Error(`invalid_runtime_manifest:${capability.capabilityId}`);
    const definition = runtime as { dependencies?: unknown; activation?: { policy?: unknown } };
    if (!Array.isArray(definition.dependencies) || definition.dependencies.some((dependency) => typeof dependency !== "string") || new Set(definition.dependencies).size !== definition.dependencies.length) throw new Error(`invalid_runtime_dependencies:${capability.capabilityId}`);
    if (!definition.activation || typeof definition.activation.policy !== "string" || !allowedActivationPolicies.has(definition.activation.policy)) throw new Error(`invalid_runtime_activation:${capability.capabilityId}`);
    for (const dependency of definition.dependencies) if (!idSet.has(dependency)) throw new Error(`unknown_runtime_dependency:${dependency}`);
  }
  const byId = new Map(capabilities.map((capability) => [capability.capabilityId, capability]));
  const visited = new Set<string>();
  const visiting = new Set<string>();
  const visit = (id: string, path: string[]) => {
    if (visiting.has(id)) throw new Error(`runtime_dependency_cycle:${[...path, id].join(" -> ")}`);
    if (visited.has(id)) return;
    visiting.add(id);
    const runtime = byId.get(id)!.manifest.runtime as { dependencies: string[] };
    for (const dependency of runtime.dependencies) visit(dependency, [...path, id]);
    visiting.delete(id);
    visited.add(id);
  };
  for (const id of ids) visit(id, []);
  return capabilities;
}

function loadRuntimeCapabilities(): RuntimeCapabilitySeed[] {
  const seedPath = join(__dirname, "../data/platform-runtime-capabilities.json");
  return validateRuntimeCapabilitySeeds(JSON.parse(readFileSync(seedPath, "utf8")));
}

async function syncRuntimeCapabilities(prisma: PrismaClient, runtimeCapabilities: RuntimeCapabilitySeed[]): Promise<void> {
  await prisma.$transaction(async (tx) => {
    for (const capability of runtimeCapabilities) {
      await tx.$queryRaw(Prisma.sql`SELECT "capabilityId" FROM "PlatformCapability" WHERE "capabilityId" = ${capability.capabilityId} FOR UPDATE`);
      const existing = await tx.platformCapability.findUnique({ where: { capabilityId: capability.capabilityId }, select: { manifest: true, state: true } });
      const existingManifest = existing?.manifest && typeof existing.manifest === "object" && !Array.isArray(existing.manifest) ? existing.manifest as Record<string, unknown> : {};
      const manifest = { ...existingManifest, ...capability.manifest };
      await tx.platformCapability.upsert({
        where: { capabilityId: capability.capabilityId },
        update: { name: capability.name, description: capability.description, manifest: manifest as Prisma.InputJsonValue },
        create: { capabilityId: capability.capabilityId, name: capability.name, description: capability.description, state: capability.state, manifest: manifest as Prisma.InputJsonValue },
      });
    }
  }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable });
}

// ─── Main export ──────────────────────────────────────────────────────────────

export async function syncCapabilities(prisma: PrismaClient, loaders: { tools?: () => ToolSnapshot[]; runtime?: () => RuntimeCapabilitySeed[] } = {}): Promise<void> {
  console.log("[sync-capabilities] Starting capability sync...");

  const runtimeCapabilities = (loaders.runtime ?? loadRuntimeCapabilities)();
  await syncRuntimeCapabilities(prisma, runtimeCapabilities);

  let tools: ToolSnapshot[];
  try {
    tools = (loaders.tools ?? loadToolsSnapshot)();
    console.log(`[sync-capabilities] Loaded ${tools.length} tools from snapshot.`);
  } catch (err) {
    console.error(
      "[sync-capabilities] Failed to load tools snapshot — skipping sync:",
      err instanceof Error ? err.message : err
    );
    return; // fail-open
  }

  const seenCapabilityIds = new Set<string>();

  for (const tool of tools) {
    try {
      const capabilityId = `platform:${tool.name}`;
      seenCapabilityIds.add(capabilityId);

      const definitionHash = computeDefinitionHash(tool);
      const riskClass = deriveRiskClass(tool);
      const auditClass = deriveAuditClass(tool);

      const existing = await prisma.platformCapability.findUnique({
        where: { capabilityId },
        select: { manifest: true },
      });

      let schemaChangedAt: string | null = null;
      if (existing) {
        const prev = existing.manifest as Record<string, unknown>;
        if (prev.definitionHash !== definitionHash) {
          schemaChangedAt = new Date().toISOString();
          console.log(`[sync-capabilities] Schema changed: ${capabilityId}`);
        } else {
          schemaChangedAt = (prev.schemaChangedAt as string | null) ?? null;
        }
      }

      const manifest: Record<string, unknown> = {
        sourceType: "internal",
        riskClass,
        auditClass,
        adapterType: "platform_tool",
        requiresExternalAccess: tool.requiresExternalAccess,
        sideEffect: tool.sideEffect,
        buildPhases: tool.buildPhases,
        integrationDependencies: [],
        definitionHash,
        schemaChangedAt,
      };

      await prisma.platformCapability.upsert({
        where: { capabilityId },
        update: {
          name: tool.name,
          description: tool.description,
          state: "active",
          manifest: manifest as Prisma.InputJsonValue,
        },
        create: {
          capabilityId,
          name: tool.name,
          description: tool.description,
          state: "active",
          manifest: manifest as Prisma.InputJsonValue,
        },
      });
    } catch (err) {
      console.error(
        `[sync-capabilities] Error upserting ${tool.name}:`,
        err instanceof Error ? err.message : err
      );
    }
  }

  // Deprecate tools that no longer exist in the snapshot
  try {
    const allCapabilities = await prisma.platformCapability.findMany({
      where: { capabilityId: { startsWith: "platform:" } },
      select: { capabilityId: true, state: true },
    });

    for (const cap of allCapabilities) {
      if (!seenCapabilityIds.has(cap.capabilityId) && cap.state !== "deprecated") {
        console.warn(
          `[sync-capabilities] Tool removed from snapshot — deprecating: ${cap.capabilityId}`
        );
        await prisma.platformCapability.update({
          where: { capabilityId: cap.capabilityId },
          data: { state: "deprecated" },
        });
      }
    }
  } catch (err) {
    console.error(
      "[sync-capabilities] Error during deprecation sweep:",
      err instanceof Error ? err.message : err
    );
  }

  console.log(
    `[sync-capabilities] Done. Synced ${seenCapabilityIds.size} platform and ${runtimeCapabilities.length} runtime capabilities.`
  );
}
