// apps/web/lib/playwright-runner.ts
// Generates and executes Playwright tests against sandbox containers.

import { exec as execCb } from "child_process";
import { promisify } from "util";

const exec = promisify(execCb);

export type UxTestStep = {
  step: string;
  passed: boolean;
  screenshotUrl: string | null;
  error: string | null;
};

export function generateTestScript(
  sandboxUrl: string,
  acceptanceCriteria: string[],
  buildId: string,
): string {
  const steps = acceptanceCriteria.map((criterion, i) => `
    await test.step('${criterion.replace(/'/g, "\\'")}', async () => {
      await page.screenshot({ path: '/results/${buildId}-step-${i}.png' });
      // Criterion: ${criterion}
      // Full assertions should be generated by the coding agent at runtime
    });
  `).join("\n");

  return `
import { test, expect } from '@playwright/test';

test('UX Acceptance: ${buildId}', async ({ page }) => {
  await page.goto('${sandboxUrl}');
  await page.waitForLoadState('networkidle');
  await page.screenshot({ path: '/results/${buildId}-initial.png' });
${steps}
});
`;
}

export async function runPlaywrightTest(buildId: string): Promise<UxTestStep[]> {
  try {
    const { stdout } = await exec(
      `docker exec playwright npx playwright test /scripts/${buildId}.spec.ts --reporter=json 2>&1 || true`,
      { timeout: 120000 },
    );
    try {
      const report = JSON.parse(stdout);
      return (report.suites?.[0]?.specs ?? []).map((spec: Record<string, unknown>, i: number) => ({
        step: (spec.title as string) ?? `Step ${i + 1}`,
        passed: (spec.ok as boolean) ?? false,
        screenshotUrl: `/results/${buildId}-step-${i}.png`,
        error: ((spec.tests as Record<string, unknown>[])?.[0] as Record<string, unknown>)?.results
          ? null
          : null,
      }));
    } catch {
      return [{ step: "Test execution", passed: false, screenshotUrl: null, error: stdout.slice(0, 500) }];
    }
  } catch (e) {
    return [{ step: "Test execution", passed: false, screenshotUrl: null, error: e instanceof Error ? e.message : String(e) }];
  }
}
