import type { FinancialProfile } from "./types";

// ─── Profile catalog ──────────────────────────────────────────────────────────

const PROFILES: Record<string, FinancialProfile> = {
  healthcare_wellness: {
    archetypeCategory: "healthcare-wellness",
    displayName: "Healthcare & Wellness",
    defaultPaymentTerms: "Due on receipt",
    defaultCurrency: "GBP",
    vatRegistered: false,
    defaultTaxRate: 0,
    dunningEnabled: true,
    dunningStyle: "standard",
    recurringBillingEnabled: true,
    invoiceTemplateStyle: "professional",
    expenseCategories: [
      "Medical Supplies",
      "Equipment Maintenance",
      "Professional Development",
      "Insurance",
      "Software Subscriptions",
      "Premises & Utilities",
    ],
    purchaseOrdersEnabled: false,
    chartOfAccountsSeed: [
      { code: "4000", name: "Consultation Revenue", type: "revenue" },
      { code: "4010", name: "Treatment Revenue", type: "revenue" },
      { code: "4020", name: "Membership Income", type: "revenue" },
      { code: "5000", name: "Medical Supplies", type: "expense" },
      { code: "5010", name: "Equipment Depreciation", type: "expense" },
      { code: "5020", name: "Professional Indemnity Insurance", type: "expense" },
      { code: "5030", name: "CPD & Training", type: "expense" },
    ],
  },

  trades_construction: {
    archetypeCategory: "trades-maintenance",
    displayName: "Trades & Construction",
    defaultPaymentTerms: "Net 14",
    defaultCurrency: "GBP",
    vatRegistered: true,
    defaultTaxRate: 20,
    dunningEnabled: true,
    dunningStyle: "aggressive",
    recurringBillingEnabled: true,
    invoiceTemplateStyle: "trade",
    expenseCategories: [
      "Materials & Supplies",
      "Tools & Equipment",
      "Vehicle Running Costs",
      "Subcontractors",
      "Insurance",
      "Site Safety & PPE",
      "Waste Disposal",
    ],
    purchaseOrdersEnabled: true,
    chartOfAccountsSeed: [
      { code: "4000", name: "Labour Revenue", type: "revenue" },
      { code: "4010", name: "Materials Revenue", type: "revenue" },
      { code: "4020", name: "Maintenance Contract Income", type: "revenue" },
      { code: "5000", name: "Materials & Supplies", type: "expense" },
      { code: "5010", name: "Subcontractor Costs", type: "expense" },
      { code: "5020", name: "Plant Hire", type: "expense" },
      { code: "5030", name: "Vehicle Expenses", type: "expense" },
    ],
  },

  professional_services: {
    archetypeCategory: "professional-services",
    displayName: "Professional Services",
    defaultPaymentTerms: "Net 30",
    defaultCurrency: "GBP",
    vatRegistered: true,
    defaultTaxRate: 20,
    dunningEnabled: true,
    dunningStyle: "standard",
    recurringBillingEnabled: true,
    invoiceTemplateStyle: "professional",
    expenseCategories: [
      "Professional Development",
      "Software & Subscriptions",
      "Office & Admin",
      "Marketing",
      "Travel & Accommodation",
      "Professional Insurance",
    ],
    purchaseOrdersEnabled: false,
    chartOfAccountsSeed: [
      { code: "4000", name: "Consulting Fees", type: "revenue" },
      { code: "4010", name: "Retainer Income", type: "revenue" },
      { code: "4020", name: "Project Revenue", type: "revenue" },
      { code: "5000", name: "Professional Subscriptions", type: "expense" },
      { code: "5010", name: "Training & CPD", type: "expense" },
      { code: "5020", name: "Marketing & Business Development", type: "expense" },
      { code: "5030", name: "Travel & Subsistence", type: "expense" },
    ],
  },

  retail: {
    archetypeCategory: "retail-goods",
    displayName: "Retail",
    defaultPaymentTerms: "Due on receipt",
    defaultCurrency: "GBP",
    vatRegistered: true,
    defaultTaxRate: 20,
    dunningEnabled: true,
    dunningStyle: "gentle",
    recurringBillingEnabled: false,
    invoiceTemplateStyle: "minimal",
    expenseCategories: [
      "Cost of Goods Sold",
      "Packaging & Shipping",
      "Shop Premises",
      "Staff Costs",
      "Marketing & Advertising",
      "Payment Processing Fees",
    ],
    purchaseOrdersEnabled: true,
    chartOfAccountsSeed: [
      { code: "4000", name: "Product Sales", type: "revenue" },
      { code: "4010", name: "Shipping & Handling Income", type: "revenue" },
      { code: "5000", name: "Cost of Goods Sold", type: "expense" },
      { code: "5010", name: "Packaging Materials", type: "expense" },
      { code: "5020", name: "Rent & Business Rates", type: "expense" },
      { code: "5030", name: "Merchant Fees", type: "expense" },
    ],
  },

  education_training: {
    archetypeCategory: "education-training",
    displayName: "Education & Training",
    defaultPaymentTerms: "50% deposit",
    defaultCurrency: "GBP",
    vatRegistered: false,
    defaultTaxRate: 0,
    dunningEnabled: true,
    dunningStyle: "standard",
    recurringBillingEnabled: true,
    invoiceTemplateStyle: "professional",
    expenseCategories: [
      "Course Materials",
      "Venue Hire",
      "Software & Platforms",
      "Marketing",
      "Tutor Fees",
      "Accreditation & Compliance",
    ],
    purchaseOrdersEnabled: false,
    chartOfAccountsSeed: [
      { code: "4000", name: "Course Fees", type: "revenue" },
      { code: "4010", name: "Subscription Income", type: "revenue" },
      { code: "4020", name: "Workshop Revenue", type: "revenue" },
      { code: "5000", name: "Course Materials", type: "expense" },
      { code: "5010", name: "Venue & Facilities", type: "expense" },
      { code: "5020", name: "External Tutor Fees", type: "expense" },
      { code: "5030", name: "Platform & Technology", type: "expense" },
    ],
  },

  nonprofit: {
    archetypeCategory: "nonprofit-community",
    displayName: "Nonprofit",
    defaultPaymentTerms: "Donation receipt",
    defaultCurrency: "GBP",
    vatRegistered: false,
    defaultTaxRate: 0,
    dunningEnabled: false,
    dunningStyle: "off",
    recurringBillingEnabled: true,
    invoiceTemplateStyle: "nonprofit",
    expenseCategories: [
      "Programme Delivery",
      "Fundraising Costs",
      "Premises & Facilities",
      "Staff & Volunteer Costs",
      "Communications",
      "Governance & Compliance",
    ],
    purchaseOrdersEnabled: false,
    chartOfAccountsSeed: [
      { code: "4000", name: "Donations & Gifts", type: "revenue" },
      { code: "4010", name: "Grant Income", type: "revenue" },
      { code: "4020", name: "Recurring Giving Income", type: "revenue" },
      { code: "5000", name: "Programme Costs", type: "expense" },
      { code: "5010", name: "Fundraising Expenditure", type: "expense" },
      { code: "5020", name: "Administration Costs", type: "expense" },
    ],
  },

  food_hospitality: {
    archetypeCategory: "food-hospitality",
    displayName: "Food & Hospitality",
    defaultPaymentTerms: "Due on receipt",
    defaultCurrency: "GBP",
    vatRegistered: true,
    defaultTaxRate: 20,
    dunningEnabled: false,
    dunningStyle: "off",
    recurringBillingEnabled: false,
    invoiceTemplateStyle: "minimal",
    expenseCategories: [
      "Food & Beverage Purchases",
      "Kitchen Equipment",
      "Premises & Rates",
      "Staff Wages",
      "Licences & Compliance",
      "Marketing & Promotions",
      "Waste Management",
    ],
    purchaseOrdersEnabled: true,
    chartOfAccountsSeed: [
      { code: "4000", name: "Food & Drink Sales", type: "revenue" },
      { code: "4010", name: "Events & Catering Revenue", type: "revenue" },
      { code: "5000", name: "Food & Beverage Cost", type: "expense" },
      { code: "5010", name: "Kitchen & Equipment", type: "expense" },
      { code: "5020", name: "Premises Costs", type: "expense" },
      { code: "5030", name: "Wage Costs", type: "expense" },
    ],
  },

  fitness_recreation: {
    archetypeCategory: "fitness-recreation",
    displayName: "Fitness & Recreation",
    defaultPaymentTerms: "Monthly direct debit",
    defaultCurrency: "GBP",
    vatRegistered: true,
    defaultTaxRate: 20,
    dunningEnabled: true,
    dunningStyle: "standard",
    recurringBillingEnabled: true,
    invoiceTemplateStyle: "minimal",
    expenseCategories: [
      "Equipment & Maintenance",
      "Facilities & Rent",
      "Staff & Instructors",
      "Insurance",
      "Marketing",
      "Software & Booking Systems",
    ],
    purchaseOrdersEnabled: false,
    chartOfAccountsSeed: [
      { code: "4000", name: "Membership Income", type: "revenue" },
      { code: "4010", name: "Class & Session Revenue", type: "revenue" },
      { code: "4020", name: "Personal Training Revenue", type: "revenue" },
      { code: "5000", name: "Equipment Costs", type: "expense" },
      { code: "5010", name: "Facility Costs", type: "expense" },
      { code: "5020", name: "Instructor Fees", type: "expense" },
    ],
  },

  beauty_personal: {
    archetypeCategory: "beauty-personal-care",
    displayName: "Beauty & Personal Care",
    defaultPaymentTerms: "Due on receipt",
    defaultCurrency: "GBP",
    vatRegistered: false,
    defaultTaxRate: 0,
    dunningEnabled: true,
    dunningStyle: "gentle",
    recurringBillingEnabled: true,
    invoiceTemplateStyle: "creative",
    expenseCategories: [
      "Product & Supplies",
      "Equipment & Tools",
      "Premises & Rent",
      "Insurance",
      "Training & Development",
      "Marketing & Social Media",
    ],
    purchaseOrdersEnabled: false,
    chartOfAccountsSeed: [
      { code: "4000", name: "Treatment Revenue", type: "revenue" },
      { code: "4010", name: "Product Sales", type: "revenue" },
      { code: "4020", name: "Package & Plan Income", type: "revenue" },
      { code: "5000", name: "Products & Consumables", type: "expense" },
      { code: "5010", name: "Equipment & Tools", type: "expense" },
      { code: "5020", name: "Salon Rent & Rates", type: "expense" },
      { code: "5030", name: "Marketing & Promotions", type: "expense" },
    ],
  },

  pet_services: {
    archetypeCategory: "pet-services",
    displayName: "Pet Services",
    defaultPaymentTerms: "Due on receipt",
    defaultCurrency: "GBP",
    vatRegistered: false,
    defaultTaxRate: 0,
    dunningEnabled: true,
    dunningStyle: "standard",
    recurringBillingEnabled: true,
    invoiceTemplateStyle: "minimal",
    expenseCategories: [
      "Pet Supplies & Products",
      "Veterinary & Insurance",
      "Premises & Kennels",
      "Vehicle & Travel",
      "Marketing",
      "Training & Certification",
    ],
    purchaseOrdersEnabled: false,
    chartOfAccountsSeed: [
      { code: "4000", name: "Service Revenue", type: "revenue" },
      { code: "4010", name: "Pet Plan Income", type: "revenue" },
      { code: "4020", name: "Product Sales", type: "revenue" },
      { code: "5000", name: "Pet Supplies", type: "expense" },
      { code: "5010", name: "Veterinary Costs", type: "expense" },
      { code: "5020", name: "Premises & Kennel Costs", type: "expense" },
      { code: "5030", name: "Vehicle & Travel", type: "expense" },
    ],
  },
};

// ─── Exported functions ───────────────────────────────────────────────────────

export function getFinancialProfile(archetypeSlug: string): FinancialProfile | null {
  return PROFILES[archetypeSlug] ?? null;
}

export function getAllProfiles(): Array<{ slug: string } & FinancialProfile> {
  return Object.entries(PROFILES).map(([slug, profile]) => ({ slug, ...profile }));
}
