-- @migration-safety: data-safe: fresh additive tables + IF NOT EXISTS; no tightening on existing rows.
-- BET-5 (BI-A1E864A5): Postgres graph mirror (nodes + edges) to retire Neo4j. Idempotent/fleet-safe.
CREATE TABLE IF NOT EXISTS "graph_node" (
  "key"    text        NOT NULL,
  "labels" text[]      NOT NULL DEFAULT '{}',
  "props"  jsonb       NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT "graph_node_pkey" PRIMARY KEY ("key")
);

CREATE TABLE IF NOT EXISTS "graph_edge" (
  "id"       bigint GENERATED BY DEFAULT AS IDENTITY,
  "src_key"  text  NOT NULL,
  "dst_key"  text  NOT NULL,
  "rel_type" text  NOT NULL,
  "props"    jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT "graph_edge_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "graph_edge_triple" ON "graph_edge" ("src_key", "dst_key", "rel_type");
CREATE INDEX IF NOT EXISTS "graph_edge_dst_rel" ON "graph_edge" ("dst_key", "rel_type");
CREATE INDEX IF NOT EXISTS "graph_edge_src_rel" ON "graph_edge" ("src_key", "rel_type");
