// POST /api/v1/edge/discovery-runs
//
// Edge Node submits a prepared discovery-run envelope. The Authority
// validates auth + envelope shape, runs the idempotency check from
// the spec's REST ingestion controls, and forwards to
// `persistSubmittedDiscoveryRun` for normalization + persistence.
//
// Phase 0 status: this route now enforces (edgeNodeId, runKey)
// idempotency and the freshness window on observedAt. The actual
// persistence wiring (calling persistSubmittedDiscoveryRun with the
// normalized envelope) is still pending — the route returns 202
// Accepted with `{ persistencePending: true }` after the gates pass,
// so the Edge Node can retry later or the test harness can validate
// the contract is wired.
//
// Spec: docs/superpowers/specs/2026-05-09-dpf-edge-node-design.md
//   § Ingestion contract: submit observations, don't trigger sweeps
//   § REST ingestion controls (Phase 0) — idempotency, freshness window

import { NextResponse, type NextRequest } from "next/server";
import { z } from "zod";

import { prisma } from "@dpf/db";

import { resolveEdgeNodeAuth } from "@/lib/auth/edge-node-token";
import { writeEdgeNodeAudit } from "@/lib/edge-node/audit";
import { checkEdgeRateLimit } from "@/lib/edge-node/rate-limit";

const ROUTE_CONTEXT = "/api/v1/edge/discovery-runs";

// Per spec § REST ingestion controls (Phase 0): observedAt must be
// within +/- this window of server time, else 400 stale_observation.
const FRESHNESS_WINDOW_MS = 24 * 60 * 60 * 1000; // 24h

const ObservationItem = z
  .object({
    observedKey: z.string().min(1),
    itemType: z.string().min(1),
    name: z.string().min(1),
    sourcePath: z.string().nullish(),
    confidence: z.number().min(0).max(1).optional(),
    rawData: z.record(z.string(), z.unknown()),
  })
  .passthrough();

const ObservationRelationship = z
  .object({
    fromObservedKey: z.string().min(1),
    toObservedKey: z.string().min(1),
    relationshipType: z.string().min(1),
    rawData: z.record(z.string(), z.unknown()).optional(),
  })
  .passthrough();

const DiscoveryRunBody = z.object({
  /** UUID generated by the Edge Node; used for idempotent submission. */
  runKey: z.string().min(1).max(120),
  /** "native-darwin" | "container-host" | etc. — agent's runtime mode. */
  agentMode: z.string().min(1).max(60),
  /** Edge Node binary version. */
  agentVersion: z.string().min(1).max(40),
  /** When the Edge Node started this sweep (ISO-8601). */
  observedAt: z.string().datetime(),
  /** Capabilities exercised in this sweep. */
  capabilities: z.array(z.string()).min(1),
  /** Discovered items + relationships. */
  items: z.array(ObservationItem).max(10000),
  relationships: z.array(ObservationRelationship).max(20000).optional(),
  /** Non-fatal warnings the Edge Node wants surfaced. */
  warnings: z.array(z.string()).optional(),
});

export async function POST(request: NextRequest): Promise<NextResponse> {
  const startedAt = Date.now();
  const authResult = await resolveEdgeNodeAuth(
    request.headers.get("authorization"),
    "discovery:submit",
  );
  if (!authResult.ok) {
    const status = discoveryAuthStatus(authResult.error);
    await writeEdgeNodeAudit({
      route: "edge.discovery_runs.submit",
      routeContext: ROUTE_CONTEXT,
      startedAt,
      edgeNodeId: null,
      nodeId: null,
      principalId: null,
      status,
      success: false,
      error: authResult.error,
      summary: { scope: "discovery:submit" },
    });
    return NextResponse.json(
      { ok: false, error: authResult.error, message: authResult.message },
      { status },
    );
  }

  // Per-node rate limit: 4/min + 60/hour per the spec § REST ingestion
  // controls. Discovery is a sweep, not a stream. Fires AFTER auth so
  // we can attribute to a specific Edge Node, and BEFORE body parsing
  // so misbehaving nodes can't burn server CPU on JSON parsing in a
  // retry storm.
  const rateLimit = checkEdgeRateLimit(
    "edge.discovery_runs.submit",
    authResult.edgeNodeRowId,
  );
  if (!rateLimit.allowed) {
    await writeEdgeNodeAudit({
      route: "edge.discovery_runs.submit",
      routeContext: ROUTE_CONTEXT,
      startedAt,
      edgeNodeId: authResult.edgeNodeRowId,
      nodeId: authResult.nodeId,
      principalId: null,
      status: 429,
      success: false,
      error: "rate_limited",
      summary: { retryAfter: rateLimit.retryAfter, ceiling: "4/min+60/hour" },
    });
    return NextResponse.json(
      {
        ok: false,
        error: "rate_limited",
        retryAfter: rateLimit.retryAfter,
      },
      {
        status: 429,
        headers: { "Retry-After": String(rateLimit.retryAfter ?? 60) },
      },
    );
  }

  let body: unknown;
  try {
    body = await request.json();
  } catch {
    await writeEdgeNodeAudit({
      route: "edge.discovery_runs.submit",
      routeContext: ROUTE_CONTEXT,
      startedAt,
      edgeNodeId: authResult.edgeNodeRowId,
      nodeId: authResult.nodeId,
      principalId: null,
      status: 400,
      success: false,
      error: "invalid_json",
    });
    return NextResponse.json(
      { ok: false, error: "invalid_json" },
      { status: 400 },
    );
  }
  const parsed = DiscoveryRunBody.safeParse(body);
  if (!parsed.success) {
    await writeEdgeNodeAudit({
      route: "edge.discovery_runs.submit",
      routeContext: ROUTE_CONTEXT,
      startedAt,
      edgeNodeId: authResult.edgeNodeRowId,
      nodeId: authResult.nodeId,
      principalId: null,
      status: 400,
      success: false,
      error: "invalid_body",
    });
    return NextResponse.json(
      {
        ok: false,
        error: "invalid_body",
        issues: parsed.error.format(),
      },
      { status: 400 },
    );
  }

  // Freshness window: reject submissions outside +/- 24h of server
  // time per spec § REST ingestion controls. Prevents back-dated
  // submissions polluting inventory history; also catches Edge Nodes
  // with badly skewed clocks before they pollute attribution.
  const observedAt = new Date(parsed.data.observedAt);
  const skewMs = Math.abs(Date.now() - observedAt.getTime());
  if (skewMs > FRESHNESS_WINDOW_MS) {
    await writeEdgeNodeAudit({
      route: "edge.discovery_runs.submit",
      routeContext: ROUTE_CONTEXT,
      startedAt,
      edgeNodeId: authResult.edgeNodeRowId,
      nodeId: authResult.nodeId,
      principalId: null,
      status: 400,
      success: false,
      error: "stale_observation",
      summary: { skewMs, observedAt: parsed.data.observedAt },
    });
    return NextResponse.json(
      {
        ok: false,
        error: "stale_observation",
        message: `observedAt must be within ${FRESHNESS_WINDOW_MS / 1000 / 3600}h of server time`,
      },
      { status: 400 },
    );
  }

  // Idempotency check per spec § REST ingestion controls:
  //   "First submission with a given (edgeNodeId, runKey) is
  //    persisted normally. Re-submission of the same pair returns
  //    the prior result snapshot — idempotent."
  // The schema's @@unique([edgeNodeId, runKey]) backs this contract;
  // the lookup uses the same composite key so a duplicate is a 200
  // (not 202) with the prior run's state.
  const prior = await prisma.discoveryRun.findUnique({
    where: {
      edgeNodeId_runKey: {
        edgeNodeId: authResult.edgeNodeRowId,
        runKey: parsed.data.runKey,
      },
    },
    select: {
      id: true,
      status: true,
      itemCount: true,
      relationshipCount: true,
      startedAt: true,
      completedAt: true,
    },
  });
  if (prior) {
    await writeEdgeNodeAudit({
      route: "edge.discovery_runs.submit",
      routeContext: ROUTE_CONTEXT,
      startedAt,
      edgeNodeId: authResult.edgeNodeRowId,
      nodeId: authResult.nodeId,
      principalId: null,
      status: 200,
      success: true,
      summary: {
        idempotentReplay: true,
        runKey: parsed.data.runKey,
        priorRunId: prior.id,
        priorStatus: prior.status,
      },
    });
    return NextResponse.json(
      {
        ok: true,
        accepted: true,
        idempotentReplay: true,
        runKey: parsed.data.runKey,
        runId: prior.id,
        status: prior.status,
        itemCount: prior.itemCount,
        relationshipCount: prior.relationshipCount,
        startedAt: prior.startedAt.toISOString(),
        completedAt: prior.completedAt?.toISOString() ?? null,
      },
      { status: 200 },
    );
  }

  // })`. Until the persistence pipeline is fully wired (it needs the
  // normalize → infer → persist chain hooked up against the route's
  // input shape), the route accepts the envelope, exercises the
  // idempotency + freshness gates, audits, and returns 202 so the
  // contract is testable end-to-end.
  await writeEdgeNodeAudit({
    route: "edge.discovery_runs.submit",
    routeContext: ROUTE_CONTEXT,
    startedAt,
    edgeNodeId: authResult.edgeNodeRowId,
    nodeId: authResult.nodeId,
    principalId: null,
    status: 202,
    success: true,
    summary: {
      runKey: parsed.data.runKey,
      agentMode: parsed.data.agentMode,
      agentVersion: parsed.data.agentVersion,
      itemCount: parsed.data.items.length,
      relationshipCount: parsed.data.relationships?.length ?? 0,
      capabilityCount: parsed.data.capabilities.length,
      persistencePending: true,
    },
  });
  return NextResponse.json(
    {
      ok: true,
      accepted: true,
      runKey: parsed.data.runKey,
      itemCount: parsed.data.items.length,
      relationshipCount: parsed.data.relationships?.length ?? 0,
      persistencePending: true,
      note: "envelope validated, auth/freshness/idempotency gates passed; full persistence pipeline wiring is a follow-up",
    },
    { status: 202 },
  );
}

function discoveryAuthStatus(
  error:
    | "missing_authorization"
    | "invalid_scheme"
    | "invalid_token_format"
    | "token_not_found"
    | "node_revoked"
    | "scope_disallowed",
): number {
  if (error === "scope_disallowed") return 403;
  return 401;
}
