// POST /api/v1/edge/discovery-runs
//
// Edge Node submits a prepared discovery-run envelope. The Authority
// runs (in order) auth → body schema → freshness window →
// (edgeNodeId, runKey) idempotency lookup → persist via
// `persistSubmittedDiscoveryRun` (normalize + dedupe + Postgres
// upsert + Neo4j projection). Returns 201 with the persistence
// summary on first-time submission, 200 with the prior snapshot on
// idempotent replay, or 4xx/5xx with an audit-logged failure.
//
// Spec: docs/superpowers/specs/2026-05-09-dpf-edge-node-design.md
//   § Ingestion contract: submit observations, don't trigger sweeps
//   § REST ingestion controls (Phase 0) — idempotency, freshness window

import { NextResponse, type NextRequest } from "next/server";
import { z } from "zod";

import { persistSubmittedDiscoveryRun, prisma } from "@dpf/db";

import { resolveEdgeNodeAuth } from "@/lib/auth/edge-node-token";
import { writeEdgeNodeAudit } from "@/lib/edge-node/audit";
import { checkEdgeRateLimit } from "@/lib/edge-node/rate-limit";

const ROUTE_CONTEXT = "/api/v1/edge/discovery-runs";

// Per spec § REST ingestion controls (Phase 0): observedAt must be
// within the operator-configured freshness window of server time, else
// 400 stale_observation.
//
// Asymmetric tolerance — past and future are bounded separately:
//
//   PAST_SEC (default 24h, matches spec § Soft-fail policy windows):
//     how old observedAt may be. The spec allows Edge Nodes to queue
//     submissions for up to 24h when the Authority is unreachable,
//     stamping the original observedAt; the queue-flush submission
//     comes through with observedAt as much as 24h before "now".
//
//   FUTURE_SEC (default 5 min, matches NTP-synced LAN clock skew):
//     how far ahead observedAt may be. A healthy NTP-synced LAN has
//     sub-second skew between hosts. Five minutes catches the case
//     of a freshly-provisioned VM that hasn't synced NTP yet without
//     blocking the install entirely — operators with chronic clock
//     drift can widen this knowingly via DPF_EDGE_FRESHNESS_FUTURE_SEC.
//     Aggressive forward skew (hours ahead) is almost always a
//     misconfigured clock and worth rejecting; back-dated forward
//     submissions also pollute attribution timelines.
//
// Both bounds are env-configurable so operators can tune for their
// environment without code changes (e.g. tighter PAST_SEC for air-gap
// deployments where 24h-stale data is suspicious by definition).
const DEFAULT_FRESHNESS_PAST_SEC = 24 * 60 * 60;   // 24 h
const DEFAULT_FRESHNESS_FUTURE_SEC = 5 * 60;        // 5 min

function parseFreshnessEnv(
  raw: string | undefined,
  fallback: number,
): number {
  if (raw === undefined || raw === "") return fallback;
  const n = Number(raw);
  if (!Number.isFinite(n) || n <= 0) return fallback;
  return Math.floor(n);
}

/**
 * Read the configured freshness window. Reads env on every call so
 * tests can override per-test via process.env without import-time
 * caching. Cheap — two env lookups + two parseInt-equivalents per
 * request.
 */
function getFreshnessConfig(): { pastMs: number; futureMs: number } {
  const pastSec = parseFreshnessEnv(
    process.env.DPF_EDGE_FRESHNESS_PAST_SEC,
    DEFAULT_FRESHNESS_PAST_SEC,
  );
  const futureSec = parseFreshnessEnv(
    process.env.DPF_EDGE_FRESHNESS_FUTURE_SEC,
    DEFAULT_FRESHNESS_FUTURE_SEC,
  );
  return { pastMs: pastSec * 1000, futureMs: futureSec * 1000 };
}

// Per spec § REST ingestion controls (Phase 0): hard payload caps to
// prevent DoS via oversized requests. The route enforces both a total
// body cap (5 MB) and a per-item rawData cap (64 KB). Above either,
// the route returns 413 Payload Too Large with an audit row capturing
// the size + cap.
const MAX_BODY_BYTES = 5 * 1024 * 1024;   // 5 MB total request body
const MAX_RAW_DATA_BYTES = 64 * 1024;     // 64 KB per item.rawData object

const ObservationItem = z
  .object({
    observedKey: z.string().min(1),
    itemType: z.string().min(1),
    name: z.string().min(1),
    sourcePath: z.string().nullish(),
    confidence: z.number().min(0).max(1).optional(),
    rawData: z.record(z.string(), z.unknown()),
  })
  .passthrough();

const ObservationRelationship = z
  .object({
    fromObservedKey: z.string().min(1),
    toObservedKey: z.string().min(1),
    relationshipType: z.string().min(1),
    rawData: z.record(z.string(), z.unknown()).optional(),
  })
  .passthrough();

const DiscoveryRunBody = z.object({
  /** UUID generated by the Edge Node; used for idempotent submission. */
  runKey: z.string().min(1).max(120),
  /** "native-darwin" | "container-host" | etc. — agent's runtime mode. */
  agentMode: z.string().min(1).max(60),
  /** Edge Node binary version. */
  agentVersion: z.string().min(1).max(40),
  /** When the Edge Node started this sweep (ISO-8601). */
  observedAt: z.string().datetime(),
  /** Capabilities exercised in this sweep. */
  capabilities: z.array(z.string()).min(1),
  /** Discovered items + relationships. */
  items: z.array(ObservationItem).max(10000),
  relationships: z.array(ObservationRelationship).max(20000).optional(),
  /** Non-fatal warnings the Edge Node wants surfaced. */
  warnings: z.array(z.string()).optional(),
});

export async function POST(request: NextRequest): Promise<NextResponse> {
  const startedAt = Date.now();
  const authResult = await resolveEdgeNodeAuth(
    request.headers.get("authorization"),
    "discovery:submit",
  );
  if (!authResult.ok) {
    const status = discoveryAuthStatus(authResult.error);
    await writeEdgeNodeAudit({
      route: "edge.discovery_runs.submit",
      routeContext: ROUTE_CONTEXT,
      startedAt,
      edgeNodeId: null,
      nodeId: null,
      principalId: null,
      status,
      success: false,
      error: authResult.error,
      summary: { scope: "discovery:submit" },
    });
    return NextResponse.json(
      { ok: false, error: authResult.error, message: authResult.message },
      { status },
    );
  }

  // Per-node rate limit: 4/min + 60/hour per the spec § REST ingestion
  // controls. Discovery is a sweep, not a stream. Fires AFTER auth so
  // we can attribute to a specific Edge Node, and BEFORE body parsing
  // so misbehaving nodes can't burn server CPU on JSON parsing in a
  // retry storm.
  const rateLimit = checkEdgeRateLimit(
    "edge.discovery_runs.submit",
    authResult.edgeNodeRowId,
  );
  if (!rateLimit.allowed) {
    await writeEdgeNodeAudit({
      route: "edge.discovery_runs.submit",
      routeContext: ROUTE_CONTEXT,
      startedAt,
      edgeNodeId: authResult.edgeNodeRowId,
      nodeId: authResult.nodeId,
      principalId: null,
      status: 429,
      success: false,
      error: "rate_limited",
      summary: { retryAfter: rateLimit.retryAfter, ceiling: "4/min+60/hour" },
    });
    return NextResponse.json(
      {
        ok: false,
        error: "rate_limited",
        retryAfter: rateLimit.retryAfter,
      },
      {
        status: 429,
        headers: { "Retry-After": String(rateLimit.retryAfter ?? 60) },
      },
    );
  }

  // Body size cap: hard limit at MAX_BODY_BYTES (5 MB). Two-stage check:
  //   1. Trust the declared Content-Length for early rejection — if the
  //      client says it's sending > 5 MB we don't need to buffer the
  //      stream to find out. A lying client gets caught at stage 2.
  //   2. Read the body as bytes (arrayBuffer) and check actual length.
  //      Required because Content-Length is optional and clients can
  //      under-declare. The arrayBuffer reads the whole body — but the
  //      Next.js runtime caps request size anyway; this gives us a
  //      precise check + audit row instead of an opaque 413 from below.
  const declaredLength = request.headers.get("content-length");
  if (declaredLength) {
    const declared = parseInt(declaredLength, 10);
    if (Number.isFinite(declared) && declared > MAX_BODY_BYTES) {
      await writeEdgeNodeAudit({
        route: "edge.discovery_runs.submit",
        routeContext: ROUTE_CONTEXT,
        startedAt,
        edgeNodeId: authResult.edgeNodeRowId,
        nodeId: authResult.nodeId,
        principalId: null,
        status: 413,
        success: false,
        error: "payload_too_large",
        summary: {
          declaredBytes: declared,
          capBytes: MAX_BODY_BYTES,
          stage: "content-length",
        },
      });
      return NextResponse.json(
        {
          ok: false,
          error: "payload_too_large",
          message: `request body exceeds ${MAX_BODY_BYTES} bytes`,
        },
        { status: 413 },
      );
    }
  }

  // Stage 2: read the actual body, verify byte count. We use
  // arrayBuffer() rather than text() so we measure bytes (not UTF-16
  // code units) — gives a precise cap independent of character
  // encoding.
  let bodyBytes: ArrayBuffer;
  try {
    bodyBytes = await request.arrayBuffer();
  } catch {
    await writeEdgeNodeAudit({
      route: "edge.discovery_runs.submit",
      routeContext: ROUTE_CONTEXT,
      startedAt,
      edgeNodeId: authResult.edgeNodeRowId,
      nodeId: authResult.nodeId,
      principalId: null,
      status: 400,
      success: false,
      error: "invalid_json",
    });
    return NextResponse.json(
      { ok: false, error: "invalid_json" },
      { status: 400 },
    );
  }
  if (bodyBytes.byteLength > MAX_BODY_BYTES) {
    await writeEdgeNodeAudit({
      route: "edge.discovery_runs.submit",
      routeContext: ROUTE_CONTEXT,
      startedAt,
      edgeNodeId: authResult.edgeNodeRowId,
      nodeId: authResult.nodeId,
      principalId: null,
      status: 413,
      success: false,
      error: "payload_too_large",
      summary: {
        actualBytes: bodyBytes.byteLength,
        capBytes: MAX_BODY_BYTES,
        stage: "buffered",
      },
    });
    return NextResponse.json(
      {
        ok: false,
        error: "payload_too_large",
        message: `request body exceeds ${MAX_BODY_BYTES} bytes`,
      },
      { status: 413 },
    );
  }

  let body: unknown;
  try {
    body = JSON.parse(new TextDecoder().decode(bodyBytes));
  } catch {
    await writeEdgeNodeAudit({
      route: "edge.discovery_runs.submit",
      routeContext: ROUTE_CONTEXT,
      startedAt,
      edgeNodeId: authResult.edgeNodeRowId,
      nodeId: authResult.nodeId,
      principalId: null,
      status: 400,
      success: false,
      error: "invalid_json",
    });
    return NextResponse.json(
      { ok: false, error: "invalid_json" },
      { status: 400 },
    );
  }
  const parsed = DiscoveryRunBody.safeParse(body);
  if (!parsed.success) {
    await writeEdgeNodeAudit({
      route: "edge.discovery_runs.submit",
      routeContext: ROUTE_CONTEXT,
      startedAt,
      edgeNodeId: authResult.edgeNodeRowId,
      nodeId: authResult.nodeId,
      principalId: null,
      status: 400,
      success: false,
      error: "invalid_body",
    });
    return NextResponse.json(
      {
        ok: false,
        error: "invalid_body",
        issues: parsed.error.format(),
      },
      { status: 400 },
    );
  }

  // Per-item rawData cap: reject if any single item.rawData object
  // exceeds MAX_RAW_DATA_BYTES (64 KB) when serialized as JSON.
  // Bounds memory damage from a runaway item while still allowing
  // rich attribute sets per typical observation. Measured via
  // TextEncoder so the cap is in actual UTF-8 bytes, not UTF-16
  // code units.
  for (let i = 0; i < parsed.data.items.length; i++) {
    const item = parsed.data.items[i]!;
    const rawDataBytes = new TextEncoder().encode(
      JSON.stringify(item.rawData),
    ).byteLength;
    if (rawDataBytes > MAX_RAW_DATA_BYTES) {
      await writeEdgeNodeAudit({
        route: "edge.discovery_runs.submit",
        routeContext: ROUTE_CONTEXT,
        startedAt,
        edgeNodeId: authResult.edgeNodeRowId,
        nodeId: authResult.nodeId,
        principalId: null,
        status: 413,
        success: false,
        error: "raw_data_too_large",
        summary: {
          itemIndex: i,
          itemObservedKey: item.observedKey,
          rawDataBytes,
          capBytes: MAX_RAW_DATA_BYTES,
        },
      });
      return NextResponse.json(
        {
          ok: false,
          error: "raw_data_too_large",
          message: `items[${i}].rawData exceeds ${MAX_RAW_DATA_BYTES} bytes (${rawDataBytes} bytes)`,
          itemIndex: i,
          itemObservedKey: item.observedKey,
        },
        { status: 413 },
      );
    }
  }

  // Freshness window: reject submissions outside the operator-
  // configured past/future bounds per spec § REST ingestion controls.
  // Prevents back-dated submissions polluting inventory history; also
  // catches Edge Nodes with badly skewed clocks before they pollute
  // attribution. Asymmetric — see top-of-file comment for rationale.
  const { pastMs, futureMs } = getFreshnessConfig();
  const observedAt = new Date(parsed.data.observedAt);
  const deltaMs = observedAt.getTime() - Date.now(); // +ve = future, -ve = past
  const tooOld = deltaMs < -pastMs;
  const tooFutureSkewed = deltaMs > futureMs;
  if (tooOld || tooFutureSkewed) {
    const direction = tooFutureSkewed ? "future" : "past";
    await writeEdgeNodeAudit({
      route: "edge.discovery_runs.submit",
      routeContext: ROUTE_CONTEXT,
      startedAt,
      edgeNodeId: authResult.edgeNodeRowId,
      nodeId: authResult.nodeId,
      principalId: null,
      status: 400,
      success: false,
      error: "stale_observation",
      summary: {
        // Keep skewMs (absolute) for backward compatibility with audit
        // consumers; add signed deltaMs + direction for new clarity.
        skewMs: Math.abs(deltaMs),
        deltaMs,
        direction,
        observedAt: parsed.data.observedAt,
        pastWindowSec: pastMs / 1000,
        futureWindowSec: futureMs / 1000,
      },
    });
    const pastH = pastMs / 1000 / 3600;
    const futureMin = futureMs / 1000 / 60;
    return NextResponse.json(
      {
        ok: false,
        error: "stale_observation",
        message:
          direction === "future"
            ? `observedAt must be at most ${futureMin.toFixed(1)}min ahead of server time (likely cause: NTP skew on the Edge Node host)`
            : `observedAt must be at most ${pastH.toFixed(1)}h before server time`,
      },
      { status: 400 },
    );
  }

  // Idempotency check per spec § REST ingestion controls:
  //   "First submission with a given (edgeNodeId, runKey) is
  //    persisted normally. Re-submission of the same pair returns
  //    the prior result snapshot — idempotent."
  // The schema's @@unique([edgeNodeId, runKey]) backs this contract;
  // the lookup uses the same composite key so a duplicate is a 200
  // (not 202) with the prior run's state.
  const prior = await prisma.discoveryRun.findUnique({
    where: {
      edgeNodeId_runKey: {
        edgeNodeId: authResult.edgeNodeRowId,
        runKey: parsed.data.runKey,
      },
    },
    select: {
      id: true,
      status: true,
      itemCount: true,
      relationshipCount: true,
      startedAt: true,
      completedAt: true,
    },
  });
  if (prior) {
    await writeEdgeNodeAudit({
      route: "edge.discovery_runs.submit",
      routeContext: ROUTE_CONTEXT,
      startedAt,
      edgeNodeId: authResult.edgeNodeRowId,
      nodeId: authResult.nodeId,
      principalId: null,
      status: 200,
      success: true,
      summary: {
        idempotentReplay: true,
        runKey: parsed.data.runKey,
        priorRunId: prior.id,
        priorStatus: prior.status,
      },
    });
    return NextResponse.json(
      {
        ok: true,
        accepted: true,
        idempotentReplay: true,
        runKey: parsed.data.runKey,
        runId: prior.id,
        status: prior.status,
        itemCount: prior.itemCount,
        relationshipCount: prior.relationshipCount,
        startedAt: prior.startedAt.toISOString(),
        completedAt: prior.completedAt?.toISOString() ?? null,
      },
      { status: 200 },
    );
  }

  // Persistence pipeline: map the wire envelope to the CollectorOutput
  // shape that persistSubmittedDiscoveryRun consumes, then normalize +
  // dedupe + write to Postgres + project to Neo4j. The submitted
  // observations are tagged sourceKind="edge_node" so admins can
  // distinguish them from portal-resident collector output.
  const submittedOutput = {
    items: parsed.data.items.map((it) => ({
      sourceKind: "edge_node" as const,
      itemType: it.itemType,
      name: it.name,
      externalRef: it.observedKey,
      ...(it.sourcePath != null ? { sourcePath: it.sourcePath } : {}),
      ...(it.confidence !== undefined ? { confidence: it.confidence } : {}),
      attributes: it.rawData,
    })),
    relationships: (parsed.data.relationships ?? []).map((r) => ({
      sourceKind: "edge_node" as const,
      relationshipType: r.relationshipType,
      fromExternalRef: r.fromObservedKey,
      toExternalRef: r.toObservedKey,
      attributes: r.rawData ?? {},
    })),
    warnings: parsed.data.warnings ?? [],
  };

  let summary;
  try {
    // `prisma as never` matches the established pattern at the bootstrap
    // ingestion sites (apps/web/app/(shell)/layout.tsx,
    // apps/web/app/api/v1/discovery/sweep/route.ts). The real prisma
    // client is structurally compatible with the DiscoverySyncClient
    // surface; the strict types don't match at compile time.
    summary = await persistSubmittedDiscoveryRun(prisma as never, {
      edgeNodeId: authResult.edgeNodeRowId,
      nodeId: authResult.nodeId,
      runKey: parsed.data.runKey,
      submittedOutput,
    });
  } catch (err) {
    // Persistence failures: audit at 500 with the redacted error.
    // Client gets a generic message so internal failure modes don't
    // leak (the audit row carries the detail for operator review).
    const errMsg = err instanceof Error ? err.message : "unknown persistence error";
    await writeEdgeNodeAudit({
      route: "edge.discovery_runs.submit",
      routeContext: ROUTE_CONTEXT,
      startedAt,
      edgeNodeId: authResult.edgeNodeRowId,
      nodeId: authResult.nodeId,
      principalId: null,
      status: 500,
      success: false,
      error: "persistence_failed",
      summary: {
        runKey: parsed.data.runKey,
        agentMode: parsed.data.agentMode,
        agentVersion: parsed.data.agentVersion,
        itemCount: parsed.data.items.length,
        relationshipCount: parsed.data.relationships?.length ?? 0,
        // The audit row keeps the detail; the client response masks it.
        errorMessage: errMsg,
      },
    });
    return NextResponse.json(
      {
        ok: false,
        error: "persistence_failed",
        message: "submission accepted but persistence failed; operator audit captured the detail",
      },
      { status: 500 },
    );
  }

  await writeEdgeNodeAudit({
    route: "edge.discovery_runs.submit",
    routeContext: ROUTE_CONTEXT,
    startedAt,
    edgeNodeId: authResult.edgeNodeRowId,
    nodeId: authResult.nodeId,
    principalId: null,
    status: 201,
    success: true,
    summary: {
      runKey: parsed.data.runKey,
      runId: summary.runId,
      agentMode: parsed.data.agentMode,
      agentVersion: parsed.data.agentVersion,
      itemCount: parsed.data.items.length,
      relationshipCount: parsed.data.relationships?.length ?? 0,
      capabilityCount: parsed.data.capabilities.length,
      createdEntities: summary.createdEntities,
      updatedEntities: summary.updatedEntities,
      createdRelationships: summary.createdRelationships,
      updatedRelationships: summary.updatedRelationships,
      createdIssues: summary.createdIssues,
    },
  });
  return NextResponse.json(
    {
      ok: true,
      accepted: true,
      runId: summary.runId,
      runKey: parsed.data.runKey,
      itemCount: parsed.data.items.length,
      relationshipCount: parsed.data.relationships?.length ?? 0,
      persisted: {
        createdEntities: summary.createdEntities,
        updatedEntities: summary.updatedEntities,
        staleEntities: summary.staleEntities,
        createdRelationships: summary.createdRelationships,
        updatedRelationships: summary.updatedRelationships,
        staleRelationships: summary.staleRelationships,
        createdIssues: summary.createdIssues,
      },
    },
    { status: 201 },
  );
}

function discoveryAuthStatus(
  error:
    | "missing_authorization"
    | "invalid_scheme"
    | "invalid_token_format"
    | "token_not_found"
    | "node_revoked"
    | "scope_disallowed",
): number {
  if (error === "scope_disallowed") return 403;
  return 401;
}
