-- BI-9D43CBEF (S4 of BI-815D40C6): type DocumentRendition.renditionKind as the
-- DocumentRenditionKind enum and full-text index rendition text.
--
-- Forward-only. Applies against any data state. Nothing in the portal wrote a
-- DocumentRendition before this slice, so the table is empty on every install
-- we know of; the statements below still handle rows, in this order:
--   1. the two legacy spellings the 2026-05-12 document-management spec named
--      ('preview-pdf', 'extracted-text') map to the new members, unless the
--      version already has the canonical row, in which case the legacy row is
--      the duplicate and goes;
--   2. anything else ('thumbnail', 'html-preview', any stray value) has no
--      member to map to and is removed before the cast.
-- A rendition is a derived projection of its DocumentVersion's content blob:
-- removing one loses no source data, and the rendition job regenerates it.

-- @migration-safety: data-safe: renditions are derived from DocumentVersion
-- content and regenerated by the rendition job; only rows with no enum member,
-- or duplicated by a canonical row, are removed.
DELETE FROM "DocumentRendition" legacy
WHERE legacy."renditionKind" IN ('preview-pdf', 'extracted-text')
  AND EXISTS (
    SELECT 1 FROM "DocumentRendition" canonical
    WHERE canonical."documentVersionId" = legacy."documentVersionId"
      AND canonical."renditionKind" = CASE legacy."renditionKind"
        WHEN 'preview-pdf' THEN 'pdf'
        ELSE 'plain_text'
      END
  );

UPDATE "DocumentRendition" SET "renditionKind" = 'pdf' WHERE "renditionKind" = 'preview-pdf';
UPDATE "DocumentRendition" SET "renditionKind" = 'plain_text' WHERE "renditionKind" = 'extracted-text';

-- @migration-safety: data-safe: see above; these values have no enum member.
DELETE FROM "DocumentRendition" WHERE "renditionKind" NOT IN ('pdf', 'plain_text');

CREATE TYPE "DocumentRenditionKind" AS ENUM ('pdf', 'plain_text');

-- @migration-safety: data-safe: every remaining value is an exact member of the new type.
ALTER TABLE "DocumentRendition"
  ALTER COLUMN "renditionKind" TYPE "DocumentRenditionKind"
  USING ("renditionKind"::"DocumentRenditionKind");

-- Full-text projection of rendition text, beside DocumentVersion.searchVector
-- (20260513010500). Generated, so Postgres keeps it current with no trigger;
-- Prisma does not model tsvector, the same as DocumentVersion.searchVector.
ALTER TABLE "DocumentRendition"
  ADD COLUMN "searchVector" tsvector GENERATED ALWAYS AS (
    to_tsvector('english', coalesce("contentText", ''))
  ) STORED;

CREATE INDEX "DocumentRendition_searchVector_idx" ON "DocumentRendition" USING GIN ("searchVector");
