export const EXPECTED_IT4IT_SUPPORTING_ROWS = [
  ["IT4IT-MAP-SF-FINANCE-001", "Financial Management: Cost Modeling; Investment"],
  ["IT4IT-MAP-SF-GRC-001", "Governance, Risk & Compliance"],
  ["IT4IT-MAP-SF-WORKFORCE-001", "Workforce Management"],
  ["IT4IT-MAP-SF-SOURCING-001", "Sourcing & Vendor Management"],
  ["IT4IT-MAP-SF-INTELLIGENCE-001", "Intelligence & Reporting"],
  ["IT4IT-MAP-SF-COLLABORATION-001", "Collaboration & Communication"],
] as const;

export const EXPECTED_IT4IT_COMPONENT_ROWS = [
  ["IT4IT-MAP-FC-POLICY-001", "Strategy to Portfolio / Strategy", "Policy", "Policy"],
  ["IT4IT-MAP-FC-STRATEGY-001", "Strategy to Portfolio / Strategy", "Strategy", "Strategic Theme; Strategic Objective"],
  ["IT4IT-MAP-FC-ENTERPRISE-ARCHITECTURE-001", "Strategy to Portfolio / Strategy", "Enterprise Architecture", "Architecture Roadmap Item; Architecture Blueprint; Value Stream"],
  ["IT4IT-MAP-FC-PORTFOLIO-BACKLOG-001", "Strategy to Portfolio / Portfolio", "Portfolio Backlog", "Portfolio Backlog Item"],
  ["IT4IT-MAP-FC-PROPOSAL-001", "Strategy to Portfolio / Portfolio", "Proposal", "Scope Agreement"],
  ["IT4IT-MAP-FC-PRODUCT-PORTFOLIO-001", "Strategy to Portfolio / Portfolio", "Product Portfolio", "Digital Product"],
  ["IT4IT-MAP-FC-PRODUCT-BACKLOG-001", "Requirement to Deploy / Develop", "Product Backlog", "Product Backlog Item"],
  ["IT4IT-MAP-FC-REQUIREMENT-001", "Requirement to Deploy / Develop", "Requirement", "Requirement"],
  ["IT4IT-MAP-FC-PRODUCT-DESIGN-001", "Requirement to Deploy / Develop", "Product Design", "Product Design"],
  ["IT4IT-MAP-FC-SOURCE-CONTROL-001", "Requirement to Deploy / Develop", "Source Control", "Source"],
  ["IT4IT-MAP-FC-PIPELINE-001", "Requirement to Deploy / Develop", "Pipeline", "Pipeline"],
  ["IT4IT-MAP-FC-BUILD-PACKAGE-001", "Requirement to Deploy / Develop", "Build Package", "Build Package"],
  ["IT4IT-MAP-FC-RELEASE-COMPOSITION-001", "Requirement to Deploy / Develop", "Release Composition", "Product Release; Product Release Blueprint"],
  ["IT4IT-MAP-FC-TEST-001", "Requirement to Deploy / Test", "Test", "Test Case; Test Plan"],
  ["IT4IT-MAP-FC-DEFECT-001", "Requirement to Deploy / Test", "Defect", "Defect"],
  ["IT4IT-MAP-FC-CONSUMPTION-EXPERIENCE-001", "Request to Fulfill / Consume", "Consumption Experience", "Interaction"],
  ["IT4IT-MAP-FC-IDENTITY-001", "Request to Fulfill / Consume", "Identity", "Identity; Entitlement"],
  ["IT4IT-MAP-FC-OFFER-001", "Request to Fulfill / Consume", "Offer", "Service Offer Catalog; Service Offer"],
  ["IT4IT-MAP-FC-ORDER-001", "Request to Fulfill / Consume", "Order", "Order; Subscription"],
  ["IT4IT-MAP-FC-CHARGEBACK-001", "Request to Fulfill / Consume", "Chargeback", "Chargeback Contract; Chargeback Record"],
  ["IT4IT-MAP-FC-CHANGE-001", "Request to Fulfill / Fulfill", "Change", "Change"],
  ["IT4IT-MAP-FC-FULFILLMENT-ORCHESTRATION-001", "Request to Fulfill / Fulfill", "Fulfillment Orchestration", "Desired Product Instance"],
  ["IT4IT-MAP-FC-RESOURCE-001", "Request to Fulfill / Fulfill", "Resource", "Resource"],
  ["IT4IT-MAP-FC-FULFILLMENT-001", "Request to Fulfill / Fulfill", "Fulfillment", "Fulfillment Book"],
  ["IT4IT-MAP-FC-USAGE-001", "Request to Fulfill / Fulfill", "Usage", "Usage Record"],
  ["IT4IT-MAP-FC-SERVICE-LEVEL-001", "Detect to Correct / Support", "Service Level", "Service Contract; KPI"],
  ["IT4IT-MAP-FC-INCIDENT-001", "Detect to Correct / Support", "Incident", "Incident"],
  ["IT4IT-MAP-FC-PROBLEM-001", "Detect to Correct / Support", "Problem", "Problem"],
  ["IT4IT-MAP-FC-KNOWLEDGE-001", "Detect to Correct / Support", "Knowledge", "Knowledge Item"],
  ["IT4IT-MAP-FC-CONFIGURATION-001", "Detect to Correct / Assure", "Configuration", "Actual Product Instance"],
  ["IT4IT-MAP-FC-MONITORING-001", "Detect to Correct / Assure", "Monitoring", "Service Monitor; Log"],
  ["IT4IT-MAP-FC-EVENT-001", "Detect to Correct / Assure", "Event", "Event"],
  ["IT4IT-MAP-FC-DIAGNOSTICS-REMEDIATION-001", "Detect to Correct / Assure", "Diagnostics & Remediation", "Runbook"],
  ["IT4IT-MAP-FC-COST-MODELING-001", "Financial Management / supporting function", "Cost Modeling", "Cost Model"],
  ["IT4IT-MAP-FC-INVESTMENT-001", "Financial Management / supporting function", "Investment", "Budget Item"],
] as const;

export const EXPECTED_IT4IT_BACKBONE_ROWS = [
  ["IT4IT-MAP-KDO-DIGITAL-PRODUCT-001", "Digital Product", "Product Portfolio"],
  ["IT4IT-MAP-KDO-PRODUCT-DESIGN-001", "Product Design", "Product Design"],
  ["IT4IT-MAP-KDO-PRODUCT-RELEASE-001", "Product Release", "Release Composition"],
  ["IT4IT-MAP-KDO-DESIRED-INSTANCE-001", "Desired Product Instance", "Fulfillment Orchestration"],
  ["IT4IT-MAP-KDO-ACTUAL-INSTANCE-001", "Actual Product Instance", "Configuration"],
  ["IT4IT-MAP-KDO-SERVICE-OFFER-001", "Service Offer", "Offer"],
  ["IT4IT-MAP-KDO-SUBSCRIPTION-001", "Subscription", "Order"],
  ["IT4IT-MAP-KDO-CHARGEBACK-001", "Chargeback Contract", "Chargeback"],
  ["IT4IT-MAP-KDO-SERVICE-CONTRACT-001", "Service Contract", "Service Level"],
] as const;

export const EXPECTED_IT4IT_CARDINALITY_ROWS = [
  ["IT4IT-MAP-CARD-PRODUCT-DESIGN-001", "Digital Product → Product Design, `1:n`", "`0..1` Product per Design; `0..*` Designs per Product; `participationSpecified=false`"],
  ["IT4IT-MAP-CARD-DESIGN-RELEASE-001", "Product Design → Product Release, `1:n`", "`0..1` Design per Release; `0..*` Releases per Design; `participationSpecified=false`"],
  ["IT4IT-MAP-CARD-RELEASE-DESIRED-001", "Product Release → Desired Product Instance, `1:n`", "`0..1` Release per Desired Instance; `0..*` Desired Instances per Release; `participationSpecified=false`"],
  ["IT4IT-MAP-CARD-DESIRED-ACTUAL-001", "Desired Product Instance → Actual Product Instance, `1:1`", "`0..1 : 0..1`; `participationSpecified=false`"],
  ["IT4IT-MAP-CARD-RELEASE-BLUEPRINT-001", "Product Release → Product Release Blueprint, §7.1.7.1 `n:1` versus §7.1.7.2 `1:n`", "under `n:1`: `0..1` Blueprint per Release and `0..*` Releases per Blueprint; under `1:n`: `0..*` Blueprints per Release and `0..1` Release per Blueprint; `participationSpecified=false`; `sourceConflict=true`"],
  ["IT4IT-MAP-CARD-OFFER-BLUEPRINT-001", "Service Offer → Product Release Blueprint, §7.1.7.2 `n:m` versus §8.1.3.2 `n:1`", "under `n:m`: `0..* : 0..*`; under `n:1`: `0..1` Blueprint per Offer and `0..*` Offers per Blueprint; `participationSpecified=false`; `sourceConflict=true`"],
  ["IT4IT-MAP-CARD-SUBSCRIPTION-OFFER-001", "Subscription → Service Offer, `n:1`", "`0..1` Offer per Subscription; `0..*` Subscriptions per Offer; `participationSpecified=false`"],
  ["IT4IT-MAP-CARD-SUBSCRIPTION-DESIRED-001", "Subscription → Desired Product Instance, `n:1`", "`0..1` Desired Instance per Subscription; `0..*` Subscriptions per Desired Instance; `participationSpecified=false`"],
  ["IT4IT-MAP-CARD-SUBSCRIPTION-CHARGEBACK-001", "Subscription → Chargeback Contract, `1:n`", "`0..*` Chargeback Contracts per Subscription; `0..1` source Subscription per contract; `participationSpecified=false`"],
  ["IT4IT-MAP-CARD-SUBSCRIPTION-SERVICE-CONTRACT-001", "Subscription → instantiated Service Contract instance, `1:1`", "`0..1 : 0..1`; `participationSpecified=false`"],
  ["IT4IT-MAP-CARD-ACTUAL-SERVICE-CONTRACT-001", "Actual Product Instance → Service Contract instance, `1:n`", "`0..*` Service Contract instances per Actual Instance; `0..1` source Actual Instance per contract; `participationSpecified=false`"],
] as const;

export const EXPECTED_CSDM_MAP_ROWS = [
  ["CSDM-MAP-STRATEGY-001", "Goal; Target; Product Idea; Planning Item", "related", "present-verified"],
  ["CSDM-MAP-VALUESTREAM-001", "Value Stream; Value Stream Stage; Business Capability; Business Process", "related", "present-verified"],
  ["CSDM-MAP-PORTFOLIO-001", "generic Portfolio; Service Portfolio; Manage Portfolio domain", "related", "present-verified"],
  ["CSDM-MAP-PRODUCT-MODEL-001", "Product Model (`cmdb_model`) and subtypes, including version-agnostic AI System Product Model", "narrow", "present-verified"],
  ["CSDM-MAP-BUSINESS-APPLICATION-001", "Business Application (`cmdb_ci_business_app`); Application Model", "broad", "present-verified"],
  ["CSDM-MAP-RELEASE-GAP-001", "no distinct release authority", "none", "absent"],
  ["CSDM-MAP-ASSET-001", "SDLC Component; AI System Digital Asset; AI Model/Dataset/Prompt Digital Assets; SBOM", "close", "present-verified"],
  ["CSDM-MAP-PACKAGE-GAP-001", "System Component Model and deployable-form descriptions", "none", "absent"],
  ["AICT-MAP-PACKAGE-001", "Package (Artifact), the deployable artifact assembled from AI Digital Assets", "close", "present-verified"],
  ["AICT-MAP-DEPLOYMENT-INTENT-GAP-001", "Deploy lifecycle stage, tasks, approvals, and target descriptions", "none", "absent"],
  ["AICT-MAP-DEPLOYMENT-OCCURRENCE-GAP-001", "deployment activity between Package (Artifact) and operational CI", "none", "absent"],
  ["CSDM-MAP-REALIZATION-001", "Product Model `model_id`; Business Application → SDLC Component → Application Service", "close", "present-verified"],
  ["CSDM-MAP-RUNTIME-001", "Service Instance; Application Service; Data Service Instance; AI Application; AI Function; Application", "close", "present-verified"],
  ["CSDM-MAP-DISCOVERY-001", "bottom-up discovery of Application, AI Application, AI Function, Application Service, and dependency topology", "related", "present-verified"],
  ["CSDM-MAP-SERVICE-001", "Business Service; Technology Management Service", "close", "present-verified"],
  ["CSDM-MAP-OFFER-001", "Business/Technology Management Service Offering; Service Commitment", "close", "present-verified"],
  ["CSDM-MAP-CONSUMPTION-001", "Service Offering Subscription; Request Catalog; Catalog Item; Install Base/usage context", "related", "present-verified"],
  ["CSDM-MAP-PHYSICAL-001", "Enterprise Good, Facility, Hardware, Consumable, OT, Facility Service Instance, Operational Process Service Instance", "related", "present-verified"],
  ["CSDM-MAP-LIFECYCLE-001", "domain progression plus Life Cycle Stage and Life Cycle Stage Status", "related", "present-verified"],
  ["CSDM-MAP-IDENTITY-GAP-001", "AI Application/AI Function and mentions of AI Agent", "none", "absent"],
  ["CSDM-MAP-BINDING-GAP-001", "`model_id` and CMDB realization/dependency relations", "none", "absent"],
  ["CSDM-MAP-WORK-GAP-001", "Business Process, Value Stream Stage, task/request/case context", "none", "absent"],
  ["CSDM-MAP-EVIDENCE-GAP-001", "monitoring, health, risk, lifecycle, and consumption telemetry", "none", "absent"],
  ["CSDM-MAP-FEDERATION-001", "internal/external provider and service-dependency topology", "related", "present-verified"],
] as const;

export const EXPECTED_CSDM_RELATION_ROWS = [
  ["CSDM-MAP-REL-SERVICE-OFFER-001", "Business/Technology Management Service has `1..*` Service Offerings; Offering derives from one parent service"],
  ["CSDM-MAP-REL-OFFER-COMMITMENT-001", "Service Offering contains `1..*` Service Commitments"],
  ["CSDM-MAP-REL-APPLICATION-SERVICE-001", "one Business Application may use several Application Services by environment/geography"],
  ["CSDM-MAP-REL-MODEL-INSTANCE-001", "a CI references `0..1` Product Model when `model_id` is populated; a Product Model may describe `0..*` instances"],
  ["CSDM-MAP-REL-VALUESTREAM-001", "each Value Stream Stage may relate to `0..*` Business Processes and `0..*` Business Capabilities through many-to-many tables; each populated relation selects one or more records"],
  ["CSDM-MAP-REL-COMPONENT-RUNTIME-001", "Business Application contains SDLC Component; SDLC Component contains Application Service; Application Service depends on runtime CIs/services"],
  ["AICT-MAP-REL-ASSET-PACKAGE-DEPLOYMENT-001", "AI Digital Asset → Package (Artifact) → repeated operational deployment/CI, `1:m:n`"],
  ["CSDM-MAP-REL-OFFER-RUNTIME-001", "Technology Offering contains Service Instance/Dynamic CI Group; Business Service Offering depends on Service Instance"],
  ["CSDM-MAP-REL-CATALOG-001", "one service may have several Catalog Items"],
] as const;
