import type { PurposeContractModule } from ".";

export const WORKROOM_PURPOSE_CONTRACTS: PurposeContractModule = [
  {
    schemaVersion: 1,
    status: "intent-ratified",
    routePath: "/ops/workrooms",
    intent: {
      primaryUser: "An operator who needs to see what work is genuinely running, what stopped, and where its activity is recorded.",
      triggeringNeed: "The stored Workroom count is much larger than the set that is still alive, and Workrooms started outside Build Studio are otherwise hard to find.",
      prerequisites: ["The user can open Operations.", "Workrooms may exist from business, coworker, or development activity."],
      job: "Distinguish live Workrooms from retained history and open the exact room whose activity needs attention.",
      successOutcome: "The operator sees a truthful live count, understands inactive and cleanup states, and reaches one Workroom activity record in one click.",
      findability: {
        parentArea: "Operations",
        entryPoints: ["/ops", "Operations > Workrooms", "/build/work"],
        navigationLayer: "Operations area tab nav",
        discoveryCue: "A Workrooms tab in Runtime & Releases and a linked live-count card in Build Studio.",
        expectedPath: ["/ops", "/ops/workrooms", "/workspace/cases/[caseKey]"],
      },
      contentRoles: {
        defaultVisibleKeys: ["live-count", "history-count", "workroom-list", "activity-link"],
        deferredRegions: [],
      },
      familyConsistency: {
        terminology: "Workroom means one coordinated unit of work. Live is evidence-derived; stored, working, and updated never substitute for live.",
        actionLocation: "Each Workroom title is its activity drill-through; cleanup status stays on the same row.",
        feedbackPrimitive: "Report-kit status badges and honest empty states; no action is implied by color alone.",
        disclosurePattern: "Live work appears first. Terminal, expired, stalled, and cleanup candidates remain in a separate history section.",
        returnBehavior: "The Workroom detail returns to the Operations inventory without changing the room.",
      },
    },
    stateScenarios: {
      "live-and-history": {
        statePredicate: "At least one Workroom is live and at least one stored Workroom is not live.",
        stateSource: { oracleKey: "route-owned-read-model", sourceRef: "apps/web/lib/work-capsules/liveness-inventory.ts" },
        essentialEvidenceKeys: ["live-count", "history-count", "workroom-list", "activity-link"],
        primaryExperience: { kind: "informational", messageKey: "workrooms.live-and-history" },
        prohibitedActionKeys: [],
        completionSignal: "Live now and History and cleanup show different rows and counts.",
        errorCorrection: "A stored row without live evidence is never counted or labeled as active.",
        recovery: { actionKey: "open-workroom-activity", routePath: "/workspace/cases/[caseKey]" },
      },
      "no-live-workrooms": {
        statePredicate: "No stored Workroom has a live liveness verdict.",
        stateSource: { oracleKey: "route-owned-read-model", sourceRef: "apps/web/lib/work-capsules/liveness-inventory.ts" },
        essentialEvidenceKeys: ["live-count", "history-count"],
        primaryExperience: { kind: "informational", messageKey: "workrooms.no-live" },
        prohibitedActionKeys: [],
        completionSignal: "The live count reads zero and retained history remains available without being called active.",
        errorCorrection: "The empty state explains that new rooms appear when work is claimed or started.",
        recovery: { actionKey: "open-workroom-definitions", routePath: "/ea/workrooms" },
      },
    },
    taskProtocol: {
      startRoute: "/ops/workrooms",
      taskPrompt: "Show me what is running now and open the room that needs attention.",
      completionOracle: "The selected Workroom detail shows its canonical activity timeline.",
      falseSuccessConditions: ["Every stored row is presented as active.", "Only development Workrooms appear.", "The title does not link to the canonical activity view."],
      acceptanceThresholds: ["Live and history are visibly separate.", "Liveness uses the shared classifier.", "A room opens in one interaction."],
    },
    ratifiedBy: { role: "owner", ref: "operator-request:mark-bodman-2026-08-24" },
    reviewRef: "BI-3023912F",
    intentEvidenceRefs: [
      { kind: "operator-request", ref: "BI-3023912F", summary: "The operator reported that Workrooms outside Build Studio were invisible and asked for one place to see ongoing activity." },
      { kind: "existing-behavior", ref: "apps/web/lib/work-capsules/liveness.ts", summary: "The shared classifier already defines true liveness from leases, PRs, builds, and sync activity rather than stored status." },
    ],
  },
  {
    schemaVersion: 1,
    status: "intent-ratified",
    routePath: "/ea/workrooms",
    intent: {
      primaryUser: "An owner or enterprise architect defining how recurring work collaborates across the four portfolios.",
      triggeringNeed: "Workroom shape, participants, queues, human triggers, and process context exist in the platform but have no coherent definition-time home.",
      prerequisites: ["The user can open Enterprise Architecture.", "Value Stream Teams are the canonical reusable coordination definitions."],
      job: "Review each portfolio's Workroom definitions and follow a definition to its process view or operational instances.",
      successOutcome: "All four portfolios stay visible and each definition exposes its shape, participants, queues, human triggers, EA links, and associated instances.",
      findability: {
        parentArea: "Enterprise Architecture",
        entryPoints: ["/ea", "Enterprise Architecture > Workrooms", "/build/work"],
        navigationLayer: "Enterprise Architecture area tab nav",
        discoveryCue: "A Workrooms tab beside Value Streams and a linked definition card in Build Studio.",
        expectedPath: ["/ea", "/ea/workrooms", "/ea/views/[id]"],
      },
      contentRoles: {
        defaultVisibleKeys: ["portfolio-bands", "definition-shape", "participants", "human-triggers", "instance-link"],
        deferredRegions: [],
      },
      familyConsistency: {
        terminology: "A definition is a Value Stream Team pattern; an instance is a Workroom. Shape, trigger, participant, queue, and portfolio retain their canonical names.",
        actionLocation: "Process and instance links sit on the definition card they explain.",
        feedbackPrimitive: "Report-kit coverage cards, status badges, and portfolio-specific empty states.",
        disclosurePattern: "The four portfolios are the primary hierarchy. Definition detail stays inside its portfolio band.",
        returnBehavior: "Opening a process or instance preserves the definition/runtime distinction and offers a normal back path.",
      },
    },
    stateScenarios: {
      "partially-defined-portfolios": {
        statePredicate: "At least one portfolio has an active Value Stream Team and at least one does not.",
        stateSource: { oracleKey: "route-owned-read-model", sourceRef: "apps/web/lib/ea/workroom-architecture.ts" },
        essentialEvidenceKeys: ["portfolio-bands", "definition-shape", "participants", "human-triggers", "instance-link"],
        primaryExperience: { kind: "informational", messageKey: "workroom-definitions.partial" },
        prohibitedActionKeys: [],
        completionSignal: "Defined portfolios show cards while uncovered portfolios show named empty states.",
        errorCorrection: "An unassigned legacy team is held in Foundational rather than disappearing from the model.",
        recovery: { actionKey: "open-operational-instances", routePath: "/ops/workrooms" },
      },
      "no-definitions": {
        statePredicate: "No active Value Stream Team exists.",
        stateSource: { oracleKey: "route-owned-read-model", sourceRef: "apps/web/lib/ea/workroom-architecture.ts" },
        essentialEvidenceKeys: ["portfolio-bands"],
        primaryExperience: { kind: "informational", messageKey: "workroom-definitions.empty" },
        prohibitedActionKeys: [],
        completionSignal: "All four portfolio bands remain visible and each explains what must be defined.",
        errorCorrection: "The page does not invent a definition or imply that a running Workroom is a reusable pattern.",
        recovery: { actionKey: "open-value-streams", routePath: "/ea/value-streams" },
      },
    },
    taskProtocol: {
      startRoute: "/ea/workrooms",
      taskPrompt: "Show me how Workrooms are shaped across the four portfolios and where their instances run.",
      completionOracle: "A definition card identifies shape, participants, queue, gate triggers, and a process or instance destination.",
      falseSuccessConditions: ["Definitions are inferred from Workroom status rows.", "A fifth definition model is introduced.", "Empty portfolios disappear."],
      acceptanceThresholds: ["Exactly four portfolio bands are visible.", "Value Stream Team remains the source of truth.", "Definitions link to Operations instances."],
    },
    ratifiedBy: { role: "owner", ref: "operator-request:mark-bodman-2026-08-24" },
    reviewRef: "BI-3023912F",
    intentEvidenceRefs: [
      { kind: "operator-request", ref: "BI-3023912F", summary: "The operator asked for an architecture-aligned place to configure and draw Workroom shapes, triggers, participants, and portfolio-level collaboration." },
      { kind: "existing-behavior", ref: "packages/db/prisma/schema/work-coordination.prisma", summary: "ValueStreamTeam already owns teamPattern, coordinationPattern, roles, HITL gates, queues, portfolio, EA links, and WorkItems." },
    ],
  },
];
