import type { ArchetypeDefinition } from "../types";

const INQUIRY_BASE_FIELDS = [
  { name: "name", label: "Full name", type: "text" as const, required: true },
  { name: "email", label: "Email", type: "email" as const, required: true },
  { name: "phone", label: "Phone", type: "tel" as const, required: false },
];

const BUSINESS_FIELDS = [
  { name: "companyName", label: "Company name", type: "text" as const, required: false },
  { name: "companySize", label: "Company size", type: "select" as const, required: false, options: ["1–10", "11–50", "51–200", "201–500", "500+"] },
  { name: "budgetRange", label: "Budget range", type: "select" as const, required: false, options: ["Under £1k", "£1k–£5k", "£5k–£20k", "£20k–£100k", "£100k+", "Not sure"] },
  { name: "currentSituation", label: "Current situation", type: "textarea" as const, required: false },
];

// Field-dispatch professional services send a credentialed person to a site,
// vehicle, or person, and produce a report as the deliverable — no parts or
// inventory. form=services + delivery=physical + onsite-plus-portal is what the
// forthcoming Field Dispatch capability reads to derive dispatch. Professional
// licensing (inspector cert, PLS, notary commission) is a capability-layer
// compliance overlay (Field Dispatch design ADR-5).
const FIELD_PROFESSIONAL_ACTIVATION: ArchetypeDefinition["activationProfile"] = {
  profileType: "standard",
  modules: ["service-operations"],
  billingReadinessMode: "none",
  customerGraph: "none",
  estateSeparation: "shared",
  axes: {
    form: "services",
    delivery: "physical",
    primaryConsumer: "household",
    consumptionChannel: "onsite-plus-portal",
    commercialModel: "transactional",
    provisioning: "account-with-billing",
    platform: "no",
  },
  portfolios: {
    foundational: { scope: "minimal" },
    manufactureAndDeliver: { scope: "primary", it4itStages: ["request-to-fulfill"] },
    forEmployees: { scope: "standard" },
    productsAndServicesSold: { scope: "primary" },
  },
};

export const professionalServicesArchetypes: ArchetypeDefinition[] = [
  {
    archetypeId: "it-managed-services",
    name: "IT Managed Services",
    category: "professional-services",
    ctaType: "inquiry",
    tags: ["IT", "managed services", "technology", "support"],
    itemTemplates: [
      { name: "Managed IT Support", description: "Monthly helpdesk and infrastructure management", priceType: "from" },
      { name: "Cybersecurity Assessment", description: "Full audit of your security posture", priceType: "fixed" },
      { name: "Cloud Migration", description: "Migrate your systems to the cloud", priceType: "quote" },
      { name: "Backup & Disaster Recovery", description: "Automated backup and recovery planning", priceType: "from" },
      { name: "Network Infrastructure", description: "Design and deployment of business networks", priceType: "quote" },
      { name: "Microsoft 365 Setup", description: "Deployment and configuration of M365 tenancy", priceType: "from" },
    ],
    sectionTemplates: [
      { type: "hero", title: "Hero", sortOrder: 0 },
      { type: "items", title: "Services", sortOrder: 1 },
      { type: "about", title: "About Us", sortOrder: 2 },
      { type: "testimonials", title: "Client Stories", sortOrder: 3 },
      { type: "contact", title: "Talk to Us", sortOrder: 4 },
    ],
    formSchema: [
      ...INQUIRY_BASE_FIELDS,
      ...BUSINESS_FIELDS,
    ],
    activationProfile: {
      profileType: "managed-service-provider",
      modules: [
        "customer-estate",
        "service-agreements",
        "billing-readiness",
        "service-operations",
        "projects",
        "lifecycle-signals",
        "integrations",
      ],
      billingReadinessMode: "prepared-not-prescribed",
      customerGraph: "separate-customer-projection",
      estateSeparation: "strict",
      axes: {
        form: "services",
        delivery: "hybrid",
        primaryConsumer: "business",
        consumptionChannel: "onsite-plus-portal",
        commercialModel: "recurring-agreement",
        provisioning: "account-and-entitlement",
        platform: "no",
      },
      portfolios: {
        foundational: { scope: "minimal" },
        manufactureAndDeliver: {
          scope: "primary",
          it4itStages: ["detect-to-correct", "deploy-to-operate", "request-to-fulfill"],
        },
        forEmployees: { scope: "standard" },
        productsAndServicesSold: { scope: "primary" },
      },
      capabilityOverrides: [
        {
          capabilityKey: "remote-support",
          applicability: "recommended",
          reason: "Consent gating is not yet automated.",
        },
      ],
      seededServiceCategories: [
        "managed-support",
        "help-desk",
        "network-monitoring",
        "endpoint-and-server-management",
        "backup-and-disaster-recovery",
        "cybersecurity",
        "cloud-services",
        "identity-and-microsoft-365",
        "projects-and-migrations",
        "advisory-and-vcio",
      ],
      seededConfigurationItemTypes: [
        {
          key: "workstation",
          label: "Workstation",
          technologySourceType: "commercial",
          defaultReviewCadenceDays: 90,
        },
        {
          key: "server",
          label: "Server",
          technologySourceType: "hybrid",
          defaultReviewCadenceDays: 60,
        },
        {
          key: "firewall",
          label: "Firewall",
          technologySourceType: "commercial",
          defaultReviewCadenceDays: 60,
        },
        {
          key: "microsoft-365-tenant",
          label: "Microsoft 365 Tenant",
          technologySourceType: "commercial",
          defaultReviewCadenceDays: 30,
          supportsLicensing: true,
          defaultChargeModel: "bundled",
        },
        {
          key: "endpoint-security-license",
          label: "Endpoint Security License",
          technologySourceType: "commercial",
          defaultReviewCadenceDays: 30,
          supportsLicensing: true,
          defaultChargeModel: "pass_through",
        },
        {
          key: "backup-agent",
          label: "Backup Agent",
          technologySourceType: "commercial",
          defaultReviewCadenceDays: 30,
          supportsLicensing: true,
          defaultChargeModel: "pass_through",
        },
        {
          key: "linux-server",
          label: "Linux Server",
          technologySourceType: "open_source",
          defaultReviewCadenceDays: 90,
        },
      ],
      seededBillingUnitTypes: [
        { key: "device", label: "Device" },
        { key: "user", label: "User" },
        { key: "server", label: "Server" },
        { key: "tenant", label: "Tenant" },
        { key: "seat", label: "Seat" },
      ],
      seededChargeModels: [
        { key: "pass_through", label: "Pass-through" },
        { key: "marked_up", label: "Marked Up" },
        { key: "bundled", label: "Bundled" },
        { key: "optional_add_on", label: "Optional Add-on" },
        { key: "included", label: "Included" },
      ],
    },
  },
  {
    archetypeId: "legal-services",
    name: "Legal Services",
    category: "professional-services",
    ctaType: "inquiry",
    tags: ["legal", "solicitor", "law", "advice"],
    itemTemplates: [
      { name: "Free Initial Consultation", description: "15-minute call to assess your legal matter", priceType: "free", bookingDurationMinutes: 15 },
      { name: "Contract Review", description: "Professional review and advice on contracts", priceType: "from" },
      { name: "Employment Law Advice", description: "Guidance on employment disputes and rights", priceType: "per-hour" },
      { name: "Property Conveyancing", description: "Residential or commercial property transactions", priceType: "quote" },
      { name: "Business Formation", description: "Company incorporation and legal structure advice", priceType: "from" },
      { name: "Litigation Support", description: "Representation in disputes and proceedings", priceType: "quote" },
    ],
    sectionTemplates: [
      { type: "hero", title: "Hero", sortOrder: 0 },
      { type: "items", title: "Services", sortOrder: 1 },
      { type: "team", title: "Our Solicitors", sortOrder: 2 },
      { type: "about", title: "About the Firm", sortOrder: 3 },
      { type: "contact", title: "Get in Touch", sortOrder: 4 },
    ],
    formSchema: [
      ...INQUIRY_BASE_FIELDS,
      { name: "matterType", label: "Type of legal matter", type: "select" as const, required: true, options: ["Employment", "Property", "Business", "Family", "Litigation", "Other"] },
      { name: "currentSituation", label: "Brief description of your matter", type: "textarea" as const, required: false },
    ],
  },
  {
    archetypeId: "accounting",
    name: "Accounting & Bookkeeping",
    category: "professional-services",
    ctaType: "inquiry",
    tags: ["accounting", "bookkeeping", "tax", "finance"],
    itemTemplates: [
      { name: "Bookkeeping", description: "Monthly bookkeeping and reconciliation", priceType: "from" },
      { name: "Annual Accounts", description: "Year-end accounts preparation and filing", priceType: "from" },
      { name: "Self Assessment Tax Return", description: "Personal tax return preparation and submission", priceType: "from" },
      { name: "VAT Returns", description: "Quarterly VAT return preparation and filing", priceType: "from" },
      { name: "Payroll", description: "Monthly payroll processing and RTI submissions", priceType: "from" },
      { name: "Business Advisory", description: "Strategic financial advice and planning", priceType: "per-hour" },
    ],
    sectionTemplates: [
      { type: "hero", title: "Hero", sortOrder: 0 },
      { type: "items", title: "Services", sortOrder: 1 },
      { type: "about", title: "About the Practice", sortOrder: 2 },
      { type: "testimonials", title: "Client Testimonials", sortOrder: 3 },
      { type: "contact", title: "Get in Touch", sortOrder: 4 },
    ],
    formSchema: [
      ...INQUIRY_BASE_FIELDS,
      { name: "companySize", label: "Business size", type: "select" as const, required: false, options: ["Sole trader", "Partnership", "Limited company (micro)", "Limited company (small)", "Limited company (medium+)"] },
      { name: "currentSituation", label: "What do you need help with?", type: "textarea" as const, required: false },
    ],
  },
  {
    archetypeId: "marketing-agency",
    name: "Marketing Agency",
    category: "professional-services",
    ctaType: "inquiry",
    tags: ["marketing", "digital", "agency", "branding"],
    itemTemplates: [
      { name: "Brand Strategy", description: "Positioning, messaging, and visual identity development", priceType: "quote" },
      { name: "Website Design & Build", description: "Custom website design and development", priceType: "from" },
      { name: "SEO & Content", description: "Organic search optimisation and content strategy", priceType: "from" },
      { name: "Paid Advertising", description: "Google Ads and social media advertising management", priceType: "from" },
      { name: "Social Media Management", description: "Full social media channel management", priceType: "from" },
      { name: "Email Marketing", description: "Campaign creation and automation", priceType: "from" },
    ],
    sectionTemplates: [
      { type: "hero", title: "Hero", sortOrder: 0 },
      { type: "items", title: "Services", sortOrder: 1 },
      { type: "gallery", title: "Our Work", sortOrder: 2 },
      { type: "about", title: "About Us", sortOrder: 3 },
      { type: "testimonials", title: "Client Results", sortOrder: 4 },
      { type: "contact", title: "Start a Project", sortOrder: 5 },
    ],
    formSchema: [
      ...INQUIRY_BASE_FIELDS,
      ...BUSINESS_FIELDS,
    ],
  },
  {
    archetypeId: "consulting",
    name: "Consulting",
    category: "professional-services",
    ctaType: "inquiry",
    tags: ["consulting", "advisory", "strategy", "business"],
    itemTemplates: [
      { name: "Discovery Workshop", description: "Half-day facilitated problem discovery session", priceType: "fixed" },
      { name: "Strategy Engagement", description: "Multi-week strategic analysis and roadmap", priceType: "quote" },
      { name: "Interim Leadership", description: "Experienced interim executive or manager", priceType: "per-hour" },
      { name: "Change Management", description: "Structured programme to manage organisational change", priceType: "quote" },
      { name: "Process Improvement", description: "Analysis and optimisation of business processes", priceType: "from" },
    ],
    sectionTemplates: [
      { type: "hero", title: "Hero", sortOrder: 0 },
      { type: "items", title: "Services", sortOrder: 1 },
      { type: "about", title: "About Us", sortOrder: 2 },
      { type: "team", title: "Our Consultants", sortOrder: 3 },
      { type: "contact", title: "Let's Talk", sortOrder: 4 },
    ],
    formSchema: [
      ...INQUIRY_BASE_FIELDS,
      { name: "companySize", label: "Organisation size", type: "select" as const, required: false, options: ["1–10", "11–50", "51–200", "201–500", "500+"] },
      { name: "budgetRange", label: "Budget range", type: "select" as const, required: false, options: ["Under £10k", "£10k–£50k", "£50k–£150k", "£150k+", "Not sure"] },
      { name: "currentSituation", label: "What challenge are you facing?", type: "textarea" as const, required: true },
    ],
  },
  {
    archetypeId: "field-inspection",
    name: "Property & Field Inspection",
    category: "professional-services",
    ctaType: "inquiry",
    tags: ["inspection", "home inspection", "property inspection", "insurance inspection", "inspector", "report"],
    itemTemplates: [
      { name: "Home Buyer's Inspection", description: "Full pre-purchase inspection with a written report", priceType: "from" },
      { name: "Pre-Listing Inspection", description: "Seller's inspection to surface issues before listing", priceType: "from" },
      { name: "Specialty Inspection", description: "Radon, mold, sewer scope, or thermal imaging add-ons", priceType: "from" },
      { name: "Insurance / 4-Point Inspection", description: "Wind mitigation and 4-point reports for insurers", priceType: "fixed" },
      { name: "Commercial Property Inspection", description: "Condition assessment for commercial buildings", priceType: "quote" },
      { name: "Re-Inspection", description: "Verify that flagged items have been repaired", priceType: "fixed" },
    ],
    sectionTemplates: [
      { type: "hero", title: "Hero", sortOrder: 0 },
      { type: "items", title: "Inspection Services", sortOrder: 1 },
      { type: "about", title: "About Us", sortOrder: 2 },
      { type: "testimonials", title: "Client Reviews", sortOrder: 3 },
      { type: "contact", title: "Schedule an Inspection", sortOrder: 4 },
    ],
    formSchema: [
      ...INQUIRY_BASE_FIELDS,
      { name: "propertyAddress", label: "Property address", type: "text" as const, required: true },
      { name: "inspectionType", label: "Inspection type", type: "select" as const, required: true, options: ["Home buyer's", "Pre-listing", "Specialty", "Insurance / 4-point", "Commercial", "Re-inspection"] },
      { name: "propertyType", label: "Property type", type: "select" as const, required: false, options: ["Single-family home", "Condo / townhouse", "Multi-family", "Commercial", "Land"] },
    ],
    activationProfile: FIELD_PROFESSIONAL_ACTIVATION,
  },
  {
    // Equipment-bound and project-flavored — surveys are scheduled jobs with a
    // plat/report deliverable, so this carries the projects module.
    archetypeId: "land-surveying",
    name: "Land Surveying",
    category: "professional-services",
    ctaType: "inquiry",
    tags: ["surveying", "land survey", "boundary survey", "topographic", "ALTA", "surveyor", "PLS"],
    itemTemplates: [
      { name: "Boundary Survey", description: "Establish and mark property lines and corners", priceType: "quote" },
      { name: "Topographic Survey", description: "Map elevations and features for design and permits", priceType: "quote" },
      { name: "ALTA / Title Survey", description: "ALTA/NSPS land title survey for commercial transactions", priceType: "quote" },
      { name: "Subdivision / Plat", description: "Survey and plat preparation for lot subdivision", priceType: "quote" },
      { name: "Elevation Certificate", description: "FEMA elevation certificate for flood insurance", priceType: "from" },
      { name: "Construction Staking", description: "Stake-out of building corners and grades on site", priceType: "from" },
    ],
    sectionTemplates: [
      { type: "hero", title: "Hero", sortOrder: 0 },
      { type: "items", title: "Survey Services", sortOrder: 1 },
      { type: "about", title: "About the Firm", sortOrder: 2 },
      { type: "contact", title: "Request a Survey", sortOrder: 3 },
    ],
    formSchema: [
      ...INQUIRY_BASE_FIELDS,
      { name: "propertyAddress", label: "Property address or parcel ID", type: "text" as const, required: true },
      { name: "surveyType", label: "Survey type", type: "select" as const, required: true, options: ["Boundary", "Topographic", "ALTA / title", "Subdivision / plat", "Elevation certificate", "Construction staking", "Not sure"] },
    ],
    activationProfile: {
      profileType: "standard",
      modules: ["service-operations", "projects"],
      billingReadinessMode: "prepared-not-prescribed",
      customerGraph: "none",
      estateSeparation: "shared",
      axes: {
        form: "services",
        delivery: "physical",
        primaryConsumer: "household",
        consumptionChannel: "onsite-plus-portal",
        commercialModel: "transactional",
        provisioning: "account-with-billing",
        platform: "no",
      },
      portfolios: {
        foundational: { scope: "minimal" },
        manufactureAndDeliver: { scope: "primary", it4itStages: ["requirement-to-deploy", "request-to-fulfill"] },
        forEmployees: { scope: "standard" },
        productsAndServicesSold: { scope: "primary" },
      },
    },
  },
  {
    // Pure go-to-person dispatch: the server/notary travels to a person to serve
    // documents or witness a signing. Jurisdiction rules are a capability-layer
    // compliance overlay.
    archetypeId: "process-serving-notary",
    name: "Process Serving & Mobile Notary",
    category: "professional-services",
    ctaType: "inquiry",
    tags: ["process serving", "process server", "mobile notary", "loan signing", "apostille", "legal support"],
    itemTemplates: [
      { name: "Serve Legal Documents", description: "Service of summons, subpoenas, and court papers", priceType: "from" },
      { name: "Rush / Same-Day Service", description: "Priority service of time-sensitive documents", priceType: "from" },
      { name: "Skip Trace", description: "Locate a hard-to-find party for service", priceType: "from" },
      { name: "Mobile Notary", description: "A notary travels to you to witness signatures", priceType: "fixed" },
      { name: "Loan Signing", description: "Notarized signing agent for real-estate closings", priceType: "fixed" },
      { name: "Court Filing & Courier", description: "File documents with the court on your behalf", priceType: "from" },
    ],
    sectionTemplates: [
      { type: "hero", title: "Hero", sortOrder: 0 },
      { type: "items", title: "Services", sortOrder: 1 },
      { type: "about", title: "About Us", sortOrder: 2 },
      { type: "contact", title: "Request Service", sortOrder: 3 },
    ],
    formSchema: [
      ...INQUIRY_BASE_FIELDS,
      { name: "serviceType", label: "Service needed", type: "select" as const, required: true, options: ["Serve documents", "Skip trace", "Mobile notary", "Loan signing", "Court filing", "Other"] },
      { name: "serviceAddress", label: "Address for service / signing", type: "text" as const, required: false },
      { name: "urgency", label: "Urgency", type: "select" as const, required: false, options: ["Standard", "Rush", "Same-day"] },
    ],
    activationProfile: FIELD_PROFESSIONAL_ACTIVATION,
  },
];
