// apps/web/lib/utils/semanticIdClassifier.ts
// Classify a DPF semantic identifier (e.g. "BI-1A2B3C4D") into its kind.
//
// Generated by the local-LLM Build Studio dispatch (opencode + qwen3-coder) for
// BI-4FF277BF and shipped via the governed path. The recognized prefixes are
// grounded in the platform's actual id-generation code (not invented):
//   BI- backlog item   (apps/web/app/api/v1/ops/backlog/route.ts)
//   EP- epic           (apps/web/app/api/v1/ops/epics/route.ts)
//   FB- feature build   (Build Studio FeatureBuild ids, e.g. FB-69231490)
//   DP- digital product (apps/web/lib/actions/products.ts)
//   WC- work capsule    (Build Studio work-capsule ids, e.g. WC-6E04A4F5)

/** Recognized DPF semantic-id prefixes → their stable kind string. */
const PREFIX_TO_KIND: Record<string, string> = {
  BI: "backlog-item",
  EP: "epic",
  FB: "feature-build",
  DP: "digital-product",
  WC: "work-capsule",
};

/**
 * Return the kind of a recognized DPF semantic identifier, or `null` when the
 * input is empty, has an unrecognized prefix, or is malformed (a recognized
 * prefix with a missing/invalid body). Pure and dependency-free. The prefix is
 * matched case-insensitively and surrounding whitespace is trimmed.
 */
export function classifySemanticId(value: string): string | null {
  if (typeof value !== "string" || value.length === 0) {
    return null;
  }

  const trimmed = value.trim();
  const hyphenIndex = trimmed.indexOf("-");
  if (hyphenIndex === -1) {
    return null;
  }

  const prefix = trimmed.substring(0, hyphenIndex).toUpperCase();
  const body = trimmed.substring(hyphenIndex + 1);

  const kind = PREFIX_TO_KIND[prefix];
  if (!kind) {
    return null;
  }

  // Body must be a non-empty run of id characters (letters, digits, hyphen).
  if (body.length === 0 || !/^[A-Za-z0-9-]+$/.test(body)) {
    return null;
  }

  return kind;
}
