/** Workroom/capsule MCP tool grants, including the drive receipt writer. */
export const WORK_CAPSULE_TOOL_GRANTS: Record<string, string[]> = {
  create_workroom: ["work_capsule_write"],
  plan_workroom_worktree: ["work_capsule_write"],
  adopt_worktree: ["work_capsule_adopt"],
  claim_backlog_item_for_work: ["work_capsule_adopt"],
  start_external_work: ["work_capsule_adopt"],
  claim_workroom_scope: ["work_capsule_write"],
  declare_break_fix: ["work_capsule_write"],
  record_workroom_evidence: ["work_capsule_write"],
  record_workroom_stage_receipt: ["workroom_drive_write"],
  record_agent_activity: ["work_capsule_write"],
  heartbeat_workroom: ["work_capsule_write"],
  update_workroom_status: ["work_capsule_write"],
  release_workroom_scope: ["work_capsule_write"],
  reassign_workroom_executor: ["work_capsule_write"],
  get_runtime_coordination_map: ["work_capsule_read"],
  list_work_capsules: ["work_capsule_read"],
  get_work_capsule: ["work_capsule_read"],
  create_work_capsule: ["work_capsule_write"],
  plan_capsule_worktree: ["work_capsule_write"],
  claim_capsule_scope: ["work_capsule_write"],
  heartbeat_capsule: ["work_capsule_write"],
  update_work_capsule_status: ["work_capsule_write"],
  release_capsule_scope: ["work_capsule_write"],
  record_capsule_evidence: ["work_capsule_write"],
  reassign_capsule_executor: ["work_capsule_write"],
};
