#!/usr/bin/env bash
# Provision the native-host Chatterbox TTS sidecar for DPF on Apple Silicon.
#
# Docker Desktop on macOS has no Metal GPU passthrough, so cloning-grade neural
# TTS must run host-native. This script stands up the Chatterbox (Resemble AI,
# MIT) OpenAI-compatible server (POST /v1/audio/speech) under a managed uv venv,
# supervises it with a launchd LaunchAgent (RunAtLoad + KeepAlive), and prints
# the .env values the portal container needs to reach it via host.docker.internal.
#
# Chatterbox is the higher-quality cloning model (matches the Windows/GPU result).
# It runs on PyTorch-MPS at ~6-8s/utterance with natural pacing on M-series.
#
# Idempotent: safe to re-run. macOS + Apple Silicon only.
# Spec: docs/superpowers/specs/2026-05-28-tts-apple-silicon-local-design.md
#
# Usage:
#   scripts/tts/setup-chatterbox-tts-macos.sh [--port 8771] [--data-root <host uploads dir>]
#                                             [--no-launchd]
set -euo pipefail

PORT="8771"
INSTALL_LAUNCHD=1
DATA_ROOT=""

# Voice tuning defaults (chosen by ear; "faster, natural tone"). These are the
# fallback when a VoiceProfile has no per-profile voiceSettings; the portal's
# per-profile sliders override them per request.
DPF_CB_EXAGGERATION="${DPF_CB_EXAGGERATION:-0.5}"
DPF_CB_CFG_WEIGHT="${DPF_CB_CFG_WEIGHT:-0.3}"
DPF_CB_TEMPERATURE="${DPF_CB_TEMPERATURE:-0.8}"
DPF_CB_SPEED="${DPF_CB_SPEED:-1.12}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
CB_HOME="${HOME}/.dpf/chatterbox"
VENV_DIR="${CB_HOME}/venv"
LOG_DIR="${CB_HOME}/logs"
SERVER_DEST="${CB_HOME}/chatterbox_server.py"
TEXT_DEST="${CB_HOME}/chatterbox_text.py"
LAUNCH_SCRIPT="${CB_HOME}/run-chatterbox.sh"
SERVER_SRC="${SCRIPT_DIR}/chatterbox_server.py"
TEXT_SRC="${SCRIPT_DIR}/chatterbox_text.py"
PLIST_TMPL="${SCRIPT_DIR}/com.dpf.chatterbox-tts.plist.tmpl"
PLIST_LABEL="local.dpf-chatterbox-tts"
PLIST_DEST="${HOME}/Library/LaunchAgents/${PLIST_LABEL}.plist"

while [ $# -gt 0 ]; do
  case "$1" in
    --port) PORT="$2"; shift 2 ;;
    --data-root) DATA_ROOT="$2"; shift 2 ;;
    --no-launchd) INSTALL_LAUNCHD=0; shift ;;
    *) echo "Unknown arg: $1" >&2; exit 2 ;;
  esac
done

log() { printf '[chatterbox setup] %s\n' "$1"; }
die() { printf '[chatterbox setup] ERROR: %s\n' "$1" >&2; exit 1; }

# --- Preconditions -----------------------------------------------------------
[ "$(uname -s)" = "Darwin" ] || die "macOS only (uname=$(uname -s))."
[ "$(uname -m)" = "arm64" ] || die "Apple Silicon (arm64) only; this host is $(uname -m)."
[ -f "$SERVER_SRC" ] || die "server source missing: ${SERVER_SRC}"
[ -f "$TEXT_SRC" ] || die "text helper source missing: ${TEXT_SRC}"

UV="$(command -v uv || true)"
[ -n "$UV" ] || UV="/opt/homebrew/bin/uv"
[ -x "$UV" ] || die "uv not found. Install with: brew install uv"

# ffmpeg decodes the portal's .webm reference clips. Auto-install when missing.
if ! command -v ffmpeg >/dev/null 2>&1 && [ ! -x /opt/homebrew/bin/ffmpeg ]; then
  if command -v brew >/dev/null 2>&1; then
    log "ffmpeg not found — installing via Homebrew"
    brew install ffmpeg >/dev/null || die "ffmpeg install failed. Install manually: brew install ffmpeg"
  else
    die "ffmpeg not found and Homebrew unavailable. Install ffmpeg: brew install ffmpeg"
  fi
fi

if [ -z "$DATA_ROOT" ]; then DATA_ROOT="${REPO_ROOT}/data/uploads"; fi

# --- Provision venv + deps ---------------------------------------------------
mkdir -p "$CB_HOME" "$LOG_DIR"
if [ ! -d "$VENV_DIR" ]; then
  log "creating uv venv (python 3.11) at ${VENV_DIR}"
  "$UV" venv --python 3.11 "$VENV_DIR" >/dev/null
fi
log "installing chatterbox-tts + server deps (reuses uv cache; first run downloads weights)"
# perth (Chatterbox's watermarker) imports pkg_resources, removed in
# setuptools>=81 -> pin <81. librosa is a perth runtime dep.
VIRTUAL_ENV="$VENV_DIR" "$UV" pip install --python "$VENV_DIR/bin/python" \
  chatterbox-tts torchaudio fastapi "uvicorn[standard]" librosa "setuptools<81" >/dev/null
log "deps installed"

# --- Install server + launch script ------------------------------------------
cp "$SERVER_SRC" "$SERVER_DEST"
log "server: ${SERVER_DEST}"
cp "$TEXT_SRC" "$TEXT_DEST"
log "text helper: ${TEXT_DEST}"

cat > "$LAUNCH_SCRIPT" <<EOF
#!/usr/bin/env bash
# Generated by scripts/tts/setup-chatterbox-tts-macos.sh — do not edit by hand.
set -euo pipefail
# launchd starts agents with a minimal PATH that excludes Homebrew; the server
# shells out to ffmpeg to decode .webm references, so put Homebrew on PATH.
export PATH="/opt/homebrew/bin:/usr/local/bin:\${PATH}"
# Voice tuning defaults (per-profile sliders in the portal override per request).
export DPF_CB_EXAGGERATION="${DPF_CB_EXAGGERATION}"
export DPF_CB_CFG_WEIGHT="${DPF_CB_CFG_WEIGHT}"
export DPF_CB_TEMPERATURE="${DPF_CB_TEMPERATURE}"
export DPF_CB_SPEED="${DPF_CB_SPEED}"
# Reference clips must live under this root; the server rejects any ref_audio
# path that escapes it (path-injection guard). Matches the portal's value.
export DPF_TTS_REFERENCE_HOST_ROOT="${DATA_ROOT}"
cd "${CB_HOME}"
# Bind to 0.0.0.0 (not 127.0.0.1) so the portal container (running in Docker Desktop's
# VM) can reach the sidecar via host.docker.internal:8771. Localhost-only bind
# works for host `curl` but breaks the Docker -> host path that the installer and
# docker-compose.macos.yml are wired for. 0.0.0.0 is safe here (TTS is local-only traffic).
exec "${VENV_DIR}/bin/python" -m uvicorn chatterbox_server:app --host 0.0.0.0 --port ${PORT}
EOF
chmod +x "$LAUNCH_SCRIPT"
log "launch script: ${LAUNCH_SCRIPT}"

# --- Install platform founder seed voice clip (for the "voice profile in the build") ---
# The seed (seedPlatformVoice) creates the VoiceProfile row + consent for
# mark-dpf-platform, but the actual reference .webm must be at the *host-visible*
# DATA_ROOT that the sidecar (and the portal's DPF_TTS_REFERENCE_HOST_ROOT) will
# use. We copy it here explicitly from the source tree the installer is running
# from. This is what made the live voice "work but not mine" (a placeholder had
# been written instead of the real bundled founder recording).
SEED_VOICE_SRC=""
for cand in \
  "${REPO_ROOT}/packages/db/data/seed-voices/mark-dpf-platform/reference.webm" \
  "${SCRIPT_DIR}/../../packages/db/data/seed-voices/mark-dpf-platform/reference.webm" \
  "${SCRIPT_DIR}/../../../packages/db/data/seed-voices/mark-dpf-platform/reference.webm"; do
  if [ -f "$cand" ] && [ -s "$cand" ]; then SEED_VOICE_SRC="$cand"; break; fi
done
SEED_VOICE_DEST_DIR="${DATA_ROOT}/voices/mark-dpf-platform"
SEED_VOICE_DEST="${SEED_VOICE_DEST_DIR}/reference.webm"
if [ -n "$SEED_VOICE_SRC" ]; then
  mkdir -p "$SEED_VOICE_DEST_DIR"
  # Force-copy if missing, or if the existing file is suspiciously small
  # (placeholder generated during earlier debugging/fixes) vs the real bundled clip.
  do_copy=0
  if [ ! -f "$SEED_VOICE_DEST" ]; then
    do_copy=1
  else
    src_sz=$(wc -c < "$SEED_VOICE_SRC" 2>/dev/null || echo 0)
    dst_sz=$(wc -c < "$SEED_VOICE_DEST" 2>/dev/null || echo 0)
    if [ "$dst_sz" -lt 20000 ] && [ "$src_sz" -gt 20000 ]; then
      do_copy=1
    fi
  fi
  if [ "$do_copy" -eq 1 ]; then
    cp -f "$SEED_VOICE_SRC" "$SEED_VOICE_DEST"
    log "installed platform founder voice clip (from build seed-voices) -> ${SEED_VOICE_DEST}"
  else
    log "platform founder voice clip already present at ${SEED_VOICE_DEST}"
  fi
else
  log "WARN: bundled seed voice clip not found under packages/db/data/seed-voices in source tree; mark-dpf-platform voice will be silent/generic until a real reference is placed at ${SEED_VOICE_DEST}"
fi

# --- Install + (re)load LaunchAgent ------------------------------------------
if [ "$INSTALL_LAUNCHD" -eq 1 ]; then
  [ -f "$PLIST_TMPL" ] || die "plist template missing: ${PLIST_TMPL}"
  mkdir -p "$(dirname "$PLIST_DEST")"
  sed -e "s|@@DPF_CB_LAUNCH_SCRIPT@@|${LAUNCH_SCRIPT}|g" \
      -e "s|@@DPF_CB_LOG_DIR@@|${LOG_DIR}|g" \
      "$PLIST_TMPL" > "$PLIST_DEST"
  # Strip macOS provenance/quarantine xattrs (and ensure perms) — these are a
  # frequent cause of "launchctl bootstrap ... Input/output error" (errno 5)
  # when the heredoc-generated files are first written by the installer or
  # setup script. Without this, the LaunchAgent fails to load even though the
  # plist and script are otherwise valid. Do it for both the executable run
  # script and the plist.
  xattr -c "$LAUNCH_SCRIPT" "$PLIST_DEST" 2>/dev/null || true
  chmod +x "$LAUNCH_SCRIPT" 2>/dev/null || true
  chmod 644 "$PLIST_DEST" 2>/dev/null || true
  launchctl bootout "gui/$(id -u)/${PLIST_LABEL}" 2>/dev/null || true
  launchctl bootstrap "gui/$(id -u)" "$PLIST_DEST" 2>/dev/null || \
    launchctl load -w "$PLIST_DEST" 2>/dev/null || true
  launchctl kickstart -k "gui/$(id -u)/${PLIST_LABEL}" 2>/dev/null || true
  log "LaunchAgent loaded: ${PLIST_DEST}"
else
  log "skipping launchd (--no-launchd); start manually: bash ${LAUNCH_SCRIPT}"
fi

# --- Health check (model load can take a few seconds on first run) -----------
log "waiting for server on 127.0.0.1:${PORT} ..."
HEALTHY=0
for _ in $(seq 1 60); do
  if curl -fsS -m 3 "http://127.0.0.1:${PORT}/v1/models" >/dev/null 2>&1; then HEALTHY=1; break; fi
  sleep 2
done
[ "$HEALTHY" -eq 1 ] && log "server healthy (HTTP 200 on /v1/models)" || log "WARN: server not responding yet — check ${LOG_DIR}/chatterbox.err.log"

# --- Print portal .env values ------------------------------------------------
cat <<EOF

==============================================================================
 Chatterbox TTS sidecar provisioned. Add these to the repo-root .env, then
 restart the portal (docker compose up -d portal):

   TTS_PROVIDER=mlx
   DPF_TTS_URL=http://host.docker.internal:${PORT}
   DPF_TTS_REFERENCE_HOST_ROOT=${DATA_ROOT}
   UPLOAD_STORAGE_PATH=${DATA_ROOT}

 (TTS_PROVIDER=mlx reuses the OpenAI-compatible adapter; it points at whichever
  host sidecar DPF_TTS_URL targets — Chatterbox here. UPLOAD_STORAGE_PATH keeps
  the DB seed (seedPlatformVoice) and portal in sync with the host sidecar root
  so the "voice profile in the build" — the real founder clip for the
  mark-dpf-platform VoiceProfile — is usable immediately.)

 The platform founder seed voice clip (from packages/db/data/seed-voices) has
 been copied into ${DATA_ROOT}/voices/mark-dpf-platform/reference.webm by this
 setup (repairing any placeholder from prior runs).

 Manage the sidecar:
   tail -f ${LOG_DIR}/chatterbox.err.log               # logs
   launchctl kickstart -k gui/$(id -u)/${PLIST_LABEL}  # restart
   launchctl bootout   gui/$(id -u)/${PLIST_LABEL}     # stop + unload
==============================================================================
EOF
