ALTER TABLE "BacklogItem" ADD COLUMN "agentId" TEXT;
ALTER TABLE "Epic" ADD COLUMN "submittedById" TEXT;
ALTER TABLE "Epic" ADD COLUMN "agentId" TEXT;
ALTER TABLE "Epic" ADD COLUMN "completedAt" TIMESTAMP(3);
ALTER TABLE "Epic" ADD CONSTRAINT "Epic_submittedById_fkey" FOREIGN KEY ("submittedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
